#!/bin/bash

set -o nounset

declare this_path; this_path="$(dirname "${BASH_SOURCE[0]}")"

QML_TARGET_PATH="/opt/victronenergy/gui/qml"
QML_SOURCE_PATH="$this_path/../src${QML_TARGET_PATH}"

[[ -d "${QML_TARGET_PATH}" ]] || { echo "Wrong Server! (path not found ${QML_TARGET_PATH})"; exit 1; }

QML_ICONS_TARGET_PATH="/opt/victronenergy/themes/ccgx/icons"
QML_ICONS_SOURCE_PATH="$this_path/../src${QML_ICONS_TARGET_PATH}"

# qml: files link all files found in $QML_ICONS_SOURCE_PATH
for source_file in "$QML_SOURCE_PATH"/*; do

	[ -f "$source_file" ] || continue
	dest_file="$(basename "$source_file")"
	echo "$source_file -> $QML_TARGET_PATH/$dest_file"
	rm -f "$QML_TARGET_PATH/$dest_file"
	ln -sf "$source_file" "$QML_TARGET_PATH/$dest_file"
done

# icons: link all files found in $QML_ICONS_SOURCE_PATH
for source_file in "$QML_ICONS_SOURCE_PATH"/*; do
	[ -f "$source_file" ] || continue
	dest_file="$(basename "$source_file")"
	rm -f "$QML_ICONS_TARGET_PATH/$dest_file"
	ln -sf "$source_file" "$QML_ICONS_TARGET_PATH/$dest_file"
done

# link the folder
# -n prevents nesting inside the target if the symlink already exists
ln -sfn "$QML_SOURCE_PATH/OpkgManager" "$QML_TARGET_PATH/OpkgManager"

# symlink service program from dev source to ve service location
# don't symlink; FIFO will error, copy from runit service to final service location
rm -rf  "/opt/victronenergy/opkg-manager"
ln -sfn "/data/dev/addons/opkg-manager/src/opt/victronenergy/opkg-manager" \
				"/opt/victronenergy/opkg-manager"

# don't symlink; FIFO will error, service from dev source to service runit location
rm -rf  "/opt/victronenergy/service/opkg-manager"
cp -r "/data/dev/addons/opkg-manager/src/opt/victronenergy/service/opkg-manager" \
					"/opt/victronenergy/service/opkg-manager"

# don't symlink; FIFO will error, copy from runit service to final service location
# this folder gets copied automatically from the above folder on os startup
rm -rf  "/service/opkg-manager"
cp -r "/opt/victronenergy/service/opkg-manager" "/service/opkg-manager"

echo "done"