#!/bin/bash

set -o nounset
 
declare this_path; this_path="$(dirname "${BASH_SOURCE[0]}")"

QML_TARGET_PATH="/opt/victronenergy/opkg-manager-service"
QML_SOURCE_PATH="$this_path/../src${QML_TARGET_PATH}"

# link the folder
rm -rf "$QML_TARGET_PATH"
ln -sf "$QML_SOURCE_PATH" "$QML_TARGET_PATH"
echo $QML_SOURCE_PATH $QML_TARGET_PATH
echo "done"