#!/usr/bin/env bash

# unreachable SC2329,SC2317
# shellcheck disable=SC2329,SC2317
# modified in subshell
# shellcheck disable=SC2031
# shellcheck disable=SC2086
# shellcheck disable=SC2119

set -o nounset

declare this_path; this_path="$(dirname "${BASH_SOURCE[0]}")"

# set path here so VENUS_ROOT_DIR is used when opkg-common is sourced
declare VENUS_ROOT_DIR="${this_path}/output/__"

. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../src/data/opkg-manager/opkg-common"

output_dir="${this_path}/output"
assets_dir="${this_path}/assets"
venus_root_dir="${VENUS_ROOT_DIR}"

#logging##############################
LOGLEVEL=$LOGLEVEL_TRACE
#LOGLEVEL=$LOGLEVEL_NONE
LOGLEVEL=$LOGLEVEL_ERROR
LOG_DATE_TIME=

#testing#############################
EXIT_ON_FAILED_TEST=1

clear_output() {
  mkdir -p "$output_dir"
  rm -fr "${output_dir:?}/"*
  #cp -r "${ASSETS_DIR}/"* "$OUTPUT_DIR/"
}

# copied all the data/opkg-manager/* files to
# the output_dir as symlinks
stage_opkg_helpers_installed() {

  local dest_path="${venus_root_dir:?}"
  local source_path="$this_path/../src"
  local -a paths

  [[ -d "$dest_path" ]] && {
    mapfile -t paths < <(find "${dest_path}") # does not return symlinks
    for path in "${paths[@]}"; do
      [[ "$path" == "$dest_path" ]] && continue
      [[ -d "$path" ]] && {
        [[ "$path" == "$dest_path/data" ]] && continue
        [[ "$path" == "$dest_path/data/opkg-manager" ]] && continue
        [[ "$path" == "$dest_path/data/opkg-manager/libs" ]] && continue

        [[ "$path" == "$dest_path/etc"* ]] && continue
      }
      [[ -L "$path" ]] || {
        [[ -d $path ]] && rm -r "$path";
        [[ -f $path ]] && rm "$path";
        #echo $path
        #echo $dest_path
        }
    done

    return
  }

  source_path="$(realpath "$source_path")"

  local paths path new_path exclude_path2 exclude_path3

  mapfile -t paths < <(find "${source_path}")
  exclude_path="$source_path/CONTROL"
  exclude_path3="$source_path/qmlplugin"

  for path in "${paths[@]}"; do
    [[ "$path" == "$exclude_path"* ]] && continue
    [[ "$path" == "$exclude_path3"* ]] && continue

    new_path="${path/$source_path/$dest_path}"

    if [[ -d "$path" ]]; then
      mkdir -p $new_path
    else
      ln -s "$path" "$new_path"
    fi
  done

  mkdir -p "${venus_root_dir:?}/etc/opkg/"

  return 0
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then
  stage_opkg_helpers_installed
fi

# update glogal vars in opkg-common

stage_fake_intalled_package() {
  local package_name=fake-package
  mkdir -p "$output_dir/data/$package_name"
  mkdir -p "opkg-common"
  rsync "$output_dir/data/$package_name"
}

###############################################################
# TESTS
__aaa() { true; }

test_add_script_to_rc_local_fails_no_script_supplied() {

  # Arrange
  #local script="# my test script"$'\n'"echo \"hello world\""
  local script=
  local stderr=

  # Act
  stderr=$(opkg_common_add_script_to_rc_local "${script}" 2>&1)

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"

  assert_eq "ERROR: no script supplied" "$stderr"
  assert_file_not_exist "$venus_root_dir/rc.local"

}
test_add_script_succeeds_script_added_to_rc_local() {

  # Arrange
  local script="# my test script"$'\n'"echo \"hello world\""
  local stderr=

  # Act
  stderr=$(opkg_common_add_script_to_rc_local "${script}" 2>&1)

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  assert_empty "$stderr"
  assert_file_exists "$rc_local_file"
  assert_file_contains "$rc_local_file" "# my test script"
  assert_file_contains "$rc_local_file" "echo \"hello world\""
}

test_add_script_succeeds_script_not_added_to_rc_local_twice() {

  # Arrange
  local script="# my test script"$'\n'"echo \"hello world\""
  local stderr=

  [[ -f "$rc_local_file" ]] && rm "$rc_local_file"

  echo "$script" > "$rc_local_file"
  local count_of=;count_of=$(grep -o "# my test script" "$rc_local_file" | wc -l)
  assert_eq 1 "${count_of}" "--"

  # Act

  stderr=$(opkg_common_add_script_to_rc_local "${script}" 2>&1)

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  assert_empty "$stderr"
  assert_file_exists "$rc_local_file"

  count_of=$(grep -o "# my test script" "$rc_local_file" | wc -l)
  assert_eq 1 "${count_of}"

  count_of=$(grep -o "echo \"hello world\"" "$rc_local_file" | wc -l)
  assert_eq 1 "${count_of}"
}

test_remove_script_fails_no_script_supplied() {

  # Arrange
  #local script="# my test script"$'\n'"echo \"hello world\""
  local script=
  local stderr=

  # Act
  stderr=$(opkg_common_remove_script_from_rc_local "${script}" 2>&1)

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"

  assert_eq "ERROR: no script supplied" "$stderr"

}

test_remove_script_succeeds_script_removed() {

  # Arrange
  local script_before="# some other script before"
  local script="# my test script"$'\n'"echo \"hello world\""
  local script_after="# some other script after"
  local stderr=

  [[ -f "$rc_local_file" ]] && rm "$rc_local_file"

  echo "$script_before" > "$rc_local_file"
  echo "$script" >> "$rc_local_file"
  echo "$script_after" >> "$rc_local_file"

  local count_of=;count_of=$(grep -o "# my test script" "$rc_local_file" | wc -l)
  assert_eq 1 "${count_of}" "--"

  # Act

  stderr=$(opkg_common_remove_script_from_rc_local "${script}" 2>&1)

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  assert_empty "$stderr"

  count_of=$(grep -o "# my test script" "$rc_local_file" | wc -l)
  assert_eq 0 "${count_of}"

  count_of=$(grep -o "echo \"hello world\"" "$rc_local_file" | wc -l)
  assert_eq 0 "${count_of}"

  assert_file_contains "$rc_local_file" "$script_before"
  assert_file_contains "$rc_local_file" "$script_after"

}

test_opkg_common_register_package_fails_package_name_empty() {

  # Arrange
  local package_name=
  local stderr=

  # Act
  stderr=$(opkg_common_register_package "${package_name}" 2>&1)

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"

  assert_eq "ERROR: no package name supplied" "$stderr"
  assert_file_not_exist "$opkg_installed_packages_file"

}

test_opkg_common_register_package_succeeds() {

  # Arrange
  local package_name="my_test_package"
  local stderr=

  # Act
  opkg_common_register_package "${package_name}"

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  assert_file_exists "$opkg_installed_packages_file"
  assert_file_contains "$opkg_installed_packages_file" "my_test_package"

}

test_opkg_common_register_package_succeeds_not_added_twice() {

  # Arrange
  local package_name="my_test_package"
  local stderr=

  [[ -f "$opkg_installed_packages_file" ]] && rm "$opkg_installed_packages_file"

  echo "$package_name" > "$opkg_installed_packages_file"
  local count_of=;count_of=$(grep -o "$package_name" "$opkg_installed_packages_file" | wc -l)
  assert_eq 1 "${count_of}" "--"

  # Act
  stderr=$(opkg_common_register_package "${package_name}" 2>&1)

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"
  assert_empty "$stderr"

  local count_of=;count_of=$(grep -o "$package_name" "$opkg_installed_packages_file" | wc -l)
  assert_eq 1 "${count_of}" "--"

}

test_remove_script_fails_no_package_name_supplied() {

  # Arrange
  local package_name=
  local stderr=

  # Act
  stderr=$(opkg_common_register_package "${package_name}" 2>&1)

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"

  assert_eq "ERROR: no package name supplied" "$stderr"

}

test_opkg_common_register_package_succeeds_package_removed_from_registered_packages_file() {

  # Arrange
  local package_name_before="the_package_before"
  local package_name="test_package"
  local package_name_after="the_package_before"
  local stderr=

  [[ -f "$opkg_installed_packages_file" ]] && rm "$opkg_installed_packages_file"

  echo "$package_name_before" > "$opkg_installed_packages_file"
  echo "$package_name" >> "$opkg_installed_packages_file"
  echo "$package_name_after" >> "$opkg_installed_packages_file"

  # Act
  stderr=$(opkg_common_unregister_package "${package_name}" 2>&1)

  # Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  assert_empty "$stderr"

  assert_file_not_contain "$opkg_installed_packages_file" "$package_name"
  assert_file_contains "$opkg_installed_packages_file" "$package_name_before"
  assert_file_contains "$opkg_installed_packages_file" "$package_name_after"

}

test_startup_script_executes_script_in_rc_local_d_folder() {
  # Arrange
  local stdout
  local startup_script_file="$opkg_rc_local_d_dir/startup"

  mkdir -p "$opkg_rc_local_d_dir/6"
  echo "echo \"my test script\"" > "$opkg_rc_local_d_dir/6/mytest_script1"
  chmod +x "$opkg_rc_local_d_dir/6/mytest_script1"

  [[ -f "$opkg_rc_local_d_dir/startup.log" ]] &&
      rm "$opkg_rc_local_d_dir/startup.log"

  # Action
  stdout=$("$startup_script_file")

  # Assert
  assert_file_exists "$opkg_rc_local_d_dir/startup.log"
  assert_eq "$stdout" "my test script"
}

test_startup_script_executes_scripts_in_correct_order() {
  # Arrange
  local stdout
  local startup_script_file="$opkg_rc_local_d_dir/startup"

  mkdir -p "$opkg_rc_local_d_dir/2" "$opkg_rc_local_d_dir/6" "$opkg_rc_local_d_dir/4" "$opkg_rc_local_d_dir/10"

  echo "echo \"script 2 yyy\"" > "$opkg_rc_local_d_dir/2/yyy"
  echo "echo \"script 2 xxx\"" > "$opkg_rc_local_d_dir/2/xxx"
  echo "echo \"script 10 bbb\"" > "$opkg_rc_local_d_dir/10/bbb"
  echo "echo \"script 6 ddd\"" > "$opkg_rc_local_d_dir/6/ddd"
  echo "echo \"script 4 uuu\"" > "$opkg_rc_local_d_dir/4/uuu"
  echo "echo \"script 6 ccc.d\"" > "$opkg_rc_local_d_dir/6/ccc.b"

  chmod +x "$opkg_rc_local_d_dir/2/yyy" "$opkg_rc_local_d_dir/2/xxx" "$opkg_rc_local_d_dir/10/bbb"
  chmod +x "$opkg_rc_local_d_dir/6/ccc.b" "$opkg_rc_local_d_dir/4/uuu" "$opkg_rc_local_d_dir/6/ddd"

  [[ -f "$opkg_rc_local_d_dir/startup.log" ]] && rm "$opkg_rc_local_d_dir/startup.log"

  # Act
  stdout=$("$startup_script_file")

  # Assert
  assert_file_exists "$opkg_rc_local_d_dir/startup.log"

  expected_order=$'script 2 xxx\nscript 2 yyy\nscript 4 uuu\nscript 6 ccc.d\nscript 6 ddd\nscript 10 bbb'

  assert_eq "$expected_order" "$stdout"
}

test_startup_script_is_run_in_seperate_processes() {
  # Arrange
  local stdout
  local startup_script_file="$opkg_rc_local_d_dir/startup"
  local pid1 pid2

  mkdir -p "$opkg_rc_local_d_dir/1"

  echo "echo \"PID1=\$BASHPID\"" > "$opkg_rc_local_d_dir/1/script1"
  echo "echo \"PID2=\$BASHPID\"" > "$opkg_rc_local_d_dir/1/script2"

  chmod +x "$opkg_rc_local_d_dir/1/script1" "$opkg_rc_local_d_dir/1/script2"

  [[ -f "$opkg_rc_local_d_dir/startup.log" ]] && rm "$opkg_rc_local_d_dir/startup.log"

  # Act
  stdout=$("$startup_script_file")

  # Assert
  assert_file_exists "$opkg_rc_local_d_dir/startup.log"

  pid1="${stdout#*PID1=*}";
  pid2="${stdout#*PID2=*}";
  assert_not_eq "$pid1" "$pid2"

}

test_ensure_package_succeeds_when_custom_packages_conf_does_not_exist() {

  # Arrange
  assert_file_not_exist "$opkg_installed_packages_file" "--"

  # Act
  opkg_common_ensure_installed

  # Assert
  assert_exitcode 0
  assert_file_not_exist "$opkg_installed_packages_file" "--"

}

test_ensure_package_succeeds_nothing_installed_when_already_installed() {
  # Arrange
  package_name="test_application"
  local test_log_file="$output_dir/test.log"

  opkg() {
    # shellcheck disable=SC2199
    if [[ "$@" == "list-installed $package_name" ]]; then
      echo "$@" >> "$test_log_file"
      echo "test_application 1.2.1"
      return 0
    fi
    echo "faked opkg: unexpected test params"
    return 0
  }
  local stdout

  [[ -f "$test_log_file" ]] && rm "$test_log_file"

  # Add test package name to opkg-manager-installed-packages.conf file
  echo "$package_name" > "$opkg_installed_packages_file"

  # Act
  opkg_common_ensure_installed

  # Assert
  assert_exitcode 0
  assert_file_exists "$test_log_file"
  assert_eq "list-installed $package_name" "$(<$test_log_file)"

}

test_ensure_package_succeeds_installed() {
  # Arrange
  package_name="test_application"
  local test_log_file="$output_dir/test.log"

  opkg() {
    # shellcheck disable=SC2199
    if [[ "$@" == "list-installed $package_name" ]]; then
      echo "$@" > "$test_log_file"
      echo "" # return nothing, when not installed
      return 0
    elif [[ "$@" == "install $package_name" ]]; then
      echo "$@" >> "$test_log_file"
      return 0
    elif [[ "$@" == "update" ]]; then
      echo "$@" >> "$test_log_file"
      return 0
    fi
    echo "faked opkg: unexpected test params"
    return 0
  }

  local stdout

  [[ -f "$test_log_file" ]] && rm "$test_log_file"

  # Add test package name to opkg-manager-installed-packages.conf file
  echo "$package_name" > "$opkg_installed_packages_file"

  # Act
  opkg_common_ensure_installed

  # Assert
  assert_exitcode 0
  assert_file_exists "$test_log_file"
  local expected="list-installed $package_name"$'\n'"update"$'\n'"install $package_name"
  assert_eq "$expected" "$(<$test_log_file)"

}

test_ensure_package_when_fs_is_writable_mount_not_called() {

  # Arrange
  package_name="test_application"
  local test_log_file="$output_dir/test.log"

  # shellcheck disable=SC2145
  mount() { echo "mount $@" > "$test_log_file"; }
  __is_fs_readonly() { return 1; } # return 1 (false) if not readonly

  opkg() {
    # shellcheck disable=SC2199
    if [[ "$@" == "list-installed $package_name" ]]; then
      return 0
    elif [[ "$@" == "install $package_name" ]]; then
      return 0
    elif [[ "$@" == "update" ]]; then
      return 0
    fi
    echo "faked opkg: unexpected test params"
    return 0
  }
  local stdout

  [[ -f "$test_log_file" ]] && rm "$test_log_file"

  # Add test package name to custom-packages.conf file
  echo "$package_name" > "$opkg_installed_packages_file"

  # Act
  opkg_common_ensure_installed

  # Assert
  assert_exitcode 0
  assert_file_not_exist "$test_log_file"

}

test_ensure_package_when_fs_is_readonly_mount_and_unmount_are_called() {

  # Arrange
  package_name="test_application"
  local test_log_file="$output_dir/test.log"

  # shellcheck disable=SC2145
  mount() {
    echo "mount $@" >> "$test_log_file"; }
  __is_fs_readonly() {
     return 0; } # return 0 (true) is readonly

  opkg() {
    # shellcheck disable=SC2199
    if [[ "$@" == "list-installed $package_name" ]]; then
      return 0
    elif [[ "$@" == "install $package_name" ]]; then
      return 0
    elif [[ "$@" == "update" ]]; then
      return 0
    fi
    echo "faked opkg: unexpected test params"
    return 0
  }

  local expected=$'mount -o remount,rw /\nmount -o remount,ro /'

  [[ -f "$test_log_file" ]] && rm "$test_log_file"

  # Add test package name to custom-packages.conf file
  echo "$package_name" > "$opkg_installed_packages_file"

  # Act
  opkg_common_ensure_installed

  # Assert
  assert_exitcode 0
  assert_file_exists "$test_log_file"
  assert_eq "$expected" "$(<$test_log_file)"

}

test_add_feed_fails_invalid_name() {

  # Arrange
  local stderr=
  local feed_file_name="${VENUS_ROOT_DIR:-}/etc/opkg/arch.conf"
  touch "$feed_file_name"
  assert_file_exists "$feed_file_name" "-"

  # Act

  stderr=$(opkg_common_feed_crud "arch.conf" "http://example.com" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "Invalid name" "$stderr"
  assert_file_exists "$feed_file_name"

}

test_feed_crud_succeeds_add_feed() {

  # Arrange
  local stderr=
  local feed_config_file="${VENUS_ROOT_DIR:-}/etc/opkg/opkg-manager.conf"
  mkdir -p "$(dirname "$feed_config_file")"
  [[ -f "$feed_config_file" ]] && rm "$feed_config_file"

  # Act
  stderr=$(opkg_common_feed_crud "custom_feed" "http://example.com" "" 2>&1)

  # Assert
  assert_exitcode 0
  assert_empty "$stderr"
  assert_file_exists "$feed_config_file"
  assert_eq 1 "$(grep -c "^src/gz custom_feed http://example.com" "$feed_config_file")"

}

test_feed_crud_fails_missing_name() {

  # Arrange
  local stderr=

  # Act
  stderr=$(opkg_common_feed_crud "" "http://example.com" "" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "Invalid name" "$stderr"

}

test_feed_crud_fails_invalid_name_chars() {

  # Arrange
  local stderr=

  # Act
  stderr=$(opkg_common_feed_crud "bad name" "http://example.com" "" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "Invalid name" "$stderr"

}

test_feed_crud_fails_invalid_old_name_chars() {

  # Arrange
  local stderr=

  # Act
  stderr=$(opkg_common_feed_crud "custom_feed" "http://example.com" "bad name" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "Invalid old name" "$stderr"

}

test_feed_crud_fails_old_name_with_delete() {

  # Arrange
  local stderr=

  # Act
  stderr=$(opkg_common_feed_crud "custom_feed" "" "old_feed" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "Invalid old name" "$stderr"

}

test_feed_crud_delete_removes_exact_match() {

  # Arrange
  local stderr=
  local feed_config_file="${VENUS_ROOT_DIR:-}/etc/opkg/opkg-manager.conf"
  mkdir -p "$(dirname "$feed_config_file")"
  cat > "$feed_config_file" <<'EOF'
src/gz name http://example.com
src/gz name2 http://example.com
EOF

  # Act
  stderr=$(opkg_common_feed_crud "name" "" "" 2>&1)

  # Assert
  assert_exitcode 0
  assert_empty "$stderr"
  assert_eq 0 "$(grep -c "^src/gz name " "$feed_config_file")"
  assert_eq 1 "$(grep -c "^src/gz name2 " "$feed_config_file")"

}

test_feed_crud_rename_removes_old_and_adds_new() {

  # Arrange
  local stderr=
  local feed_config_file="${VENUS_ROOT_DIR:-}/etc/opkg/opkg-manager.conf"
  mkdir -p "$(dirname "$feed_config_file")"
  echo "src/gz old_feed http://old.example.com" > "$feed_config_file"

  # Act
  stderr=$(opkg_common_feed_crud "new_feed" "http://new.example.com" "old_feed" 2>&1)

  # Assert
  assert_exitcode 0
  assert_empty "$stderr"
  assert_eq 0 "$(grep -c "^src/gz old_feed " "$feed_config_file")"
  assert_eq 1 "$(grep -c "^src/gz new_feed http://new.example.com" "$feed_config_file")"

}


pre_test_runner() {
  clear_output
  stage_opkg_helpers_installed
}
post_test_runner() {
true
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then

  #declare cur_func; cur_func=$(grep -E '^cur_test_[^[:space:]]*\(\).*' "${BASH_SOURCE[0]}")
  #cur_func=${cur_func%%\(\)*}
  #[[ "$cur_func" ]] && { "$cur_func"; exit 0; }

  test_runner_all --summary "" #"^cur_test_*"
fi