#!/usr/bin/env bash

set -o nounset

this_path="$(dirname "${BASH_SOURCE[0]}")"
 
. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../src/data/opkg-manager/libs/core-lib"
. "$this_path/../src/data/opkg-manager/libs/log-lib"
. "$this_path/../src/data/opkg-manager/serial-device-installer"
 
this_dir_full="$(core_lib_realpath_nosymlinks "${this_path}")"
output_dir="${this_dir_full}/output"
assets_dir="${this_dir_full}/assets"

# shellcheck disable=SC2120
stage_default_vars() {
  DEVICE_SERVICE_NAME="${1:-dummy_service}"
  DEVICE_SERVICE_MAPPING_NAME="ve_${DEVICE_SERVICE_NAME}"
  DEVICE_TTY=
  SERVICE_PATH="$output_dir/service"
  SERIAL_STARTER_START_SERVICE_PATH="$output_dir/serial-starter"

  SERIAL_STARTER_RULES_FILE="$output_dir/serial-starter.rules"
  SERIAL_STARTER_CONFIG_FILE="$output_dir/serial-starter.conf"
  SERIAL_STARTER_RULES_TEXT_MATCH='RUN+="/opt/victronenergy/serial-starter/cleanup.sh %k"'
  DEVICE_UDEV_PROPS="ID_BUS,ID_VENDOR,ID_MODEL,ID_SERIAL"
  USE_UDEVADM_MONITOR="1"
  USB_TIMEOUT=3
}
clear_output() {
  mkdir -p "$output_dir"
  rm -fr "${output_dir:?}/"*
  #cp -r "${ASSETS_DIR}/"* "$OUTPUT_DIR/"
}
install() { 
  
  # Arrange
  stage_default_vars
  clear_output
  clear

  cp "$assets_dir/serial-starter.rules" "$output_dir/serial-starter.rules"
  cp "$assets_dir/serial-starter.conf" "$output_dir/serial-starter.conf"
  chmod +w+r "${output_dir}/"*

  DEVICE_TTY=
  DEVICE_UDEV_PROPS="ID_BUS=usb,ID_VENDOR=FTDI,ID_MODEL=FT232R_USB_UAR,ID_SERIAL=FTDI_FT232R_USB_UART_A5069RR4"

  # Act
  serial_device_installer_install
  echo "DEVICE_TTY=$DEVICE_TTY"

}
install