#!/usr/bin/env bash

# unreachable SC2329,SC2317
# shellcheck disable=SC2329,SC2317
# modified in subshell
# shellcheck disable=SC2031
# shellcheck disable=SC2086
# shellcheck disable=SC2119

set -o nounset

this_path="$(dirname "${BASH_SOURCE[0]}")"

declare IGNORE_CONF_LIB=

. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../src/data/opkg-manager/libs/core-lib"
#. "$this_path/../src/data/opkg-manager/libs/log-lib"
if [[ -f "$this_path/../src/data/opkg-manager/libs/conf-lib" ]]; then
. "$this_path/../src/data/opkg-manager/libs/conf-lib"
else
  IGNORE_CONF_LIB=1
fi

. "$this_path/../src/data/opkg-manager/serial-device-installer"

this_dir_full="$(core_lib_realpath_nosymlinks "${this_path}" 2>/dev/null || true)"
[[ -z "$this_dir_full" ]] && this_dir_full="$(readlink -f "${this_path}" 2>/dev/null || pwd)"
output_dir="/tmp/opkg-manager-serial-device-installer-tests"
assets_dir="${this_dir_full}/assets"

#if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  #printf "\033c" # clear
#fi

clear_output() {
  rm -rf -- "${output_dir:?}"
  mkdir -p "$output_dir"
  #cp -r "${ASSETS_DIR}/"* "$OUTPUT_DIR/"
}

# stages the directories inside the output directory for starting services
stage_service_paths() {
  output_path_len="${#output_dir}"
  start_path="${SERIAL_STARTER_START_SERVICE_PATH:0:$output_path_len}"

  # ensure the path is inside the output folder
  [[ "$start_path" != "${output_dir}" ]] && {
    echo "stage_service_paths:Error invalid SERIAL_STARTER_START_SERVICE_PATH path!"; exit 1; }

  mkdir -p "$SERIAL_STARTER_START_SERVICE_PATH"

  rm -f $SERIAL_STARTER_START_SERVICE_PATH/*
  rm -f "/var/lock/serial-starter/*"
  rm -f "/run/lock/serial-starter/*"

  start_path="${SERVICE_PATH:0:$output_path_len}"
  [[ "$start_path" != "${output_dir}" ]] && {
    echo "stage_service_paths:Error invalid SERVICE_PATH path!"; exit 1; }

  mkdir -p "$SERVICE_PATH"
}

stage_get_expected_serial_starter_header_and_rule() {
  local -n _header="${1}"; _header='# sid:ef2d:dummy_service'
  local -n _rule="${2}"; _rule='ACTION=="add", ENV{ID_BUS}=="usb", ENV{ID_MODEL}=="FT232R_USB_UART", ENV{ID_SERIAL}=="FTDI_FT232R_USB_UART_B0001AJ7", ENV{ID_VENDOR}=="FTDI", ENV{VE_SERVICE}="ve_dummy_service", ENV{SERIAL_DEVICE_ID}="ef2d"'
}
stage_get_expected_ve_service_mapping() {
  local -n _mapping="${1}"; _mapping='service ve_dummy_service dummy_service'
}
stage_get_filled_UDEVADM_PROPS() {
  local -n _udevadm_props="${1}"
  _udevadm_props='ID_MODEL=FT232R_USB_UART,ID_SERIAL=FTDI_FT232R_USB_UART_B0001AJ7,ID_BUS=usb,ID_VENDOR=FTDI'
}
stage_get_filled_UDEVADM_PROPS_no_match() {
  local -n _udevadm_props="${1}"
  _udevadm_props='ID_MODEL=THIS_WONT_MATCH,ID_SERIAL=FTDI_FT232R_USB_UART_B0001AJ7,ID_BUS=usb,ID_VENDOR=FTDI'
}
# shellcheck disable=SC2120
stage_reset_vars() {
  local -a vars=()
  # shellcheck disable=SC2199
  if [[ -n "$@" ]]; then
    vars=(DEVICE_SID DEVICE_SERVICE_NAME DEVICE_SERVICE_MAPPING_NAME DEVICE_TTY SERVICE_PATH SERIAL_STARTER_START_SERVICE_PATH
          SERIAL_STARTER_RULES_FILE SERIAL_STARTER_RULES_FILE_SYMLINK SERIAL_STARTER_CONFIG_FILE
          DEVICE_UDEV_PROPS USE_UDEVADM_MONITOR)
  else
    vars=("$@")
  fi

  for var in "${vars[@]}"; do unset -v "$var" ;done;
}

# shellcheck disable=SC2120
stage_default_vars() {
  DEVICE_SID= #ef2d
  _TTY=ttyUSB0
  DEVICE_SERVICE_NAME="${1:-dummy_service}"
  DEVICE_SERVICE_MAPPING_NAME="ve_${DEVICE_SERVICE_NAME}"
  DEVICE_TTY=
  SERVICE_PATH="$output_dir/service"
  SERIAL_STARTER_START_SERVICE_PATH="$output_dir/serial-starter"
  #SERIAL_STARTER_RULE=
  SERIAL_STARTER_RULES_FILE="$output_dir/serial-starter.rules"
  SERIAL_STARTER_RULES_FILE_SYMLINK="$output_dir/opkg-manager-serial-starter.rules"
  SERIAL_STARTER_CONFIG_FILE="$output_dir/serial-starter.conf"
  DEVICE_UDEV_PROPS="ID_BUS,ID_VENDOR,ID_MODEL,ID_SERIAL"
  USE_UDEVADM_MONITOR="1"
}

# shellcheck disable=SC2120
stage_files() {

  local args=("$@")
  (( ${#args[@]} == 0 )) && {
    args=("serial-device-installer.test1.conf" "serial-device-installer.test1.conf.schema")
  }

  clear_output

  for file in "${args[@]}"; do
    [ -f "${assets_dir}/${file}" ] || {
      assert_file_exists "$file" "stage_file not found" >&2; return 1; }
    cp "${assets_dir}/${file}" "${output_dir}/${file}"
    chmod +w "${output_dir}/${file}"
  done

  return 0
}


#logging##############################
LOGLEVEL=$LOGLEVEL_TRACE
#LOGLEVEL=$LOGLEVEL_NONE
LOGLEVEL=$LOGLEVEL_ERROR
LOG_DATE_TIME=

#testing#############################
EXIT_ON_FAILED_TEST=
silent="--"

#conf_file="${output_dir}/installer.conf"
test_SERVICE_NAME='dummy_service'
# shellcheck disable=SC2034
test_SERVICE_MAPPING_NAME="ve_${test_SERVICE_NAME}"
#test_TTY='ttyUSB0'
#test_SERIAL_STARTER_RULES_FILE="${output_dir}/serial-starter.rules"
#SERIAL_STARTER_CONFIG_FILE="${output_dir}/serial-starter.conf"

##############################################################################
# mocked exe calls
svc() {
  echo "    fake-svc called with args:$*"
}

callback_get_tty_port() {
  local -n out_tty="${1}"
  out_tty="${_TTY:-}"
  [[ -n "${out_tty}" ]] || return 1
  return 0
}

#fake overriden udevadm method
udevadm() {

  # shellcheck disable=SC2199
  if [[ "$@" == "info --name=/dev/${_TTY:-} --query=property" ]]; then
     # echo load from file to get consistant test results even when usb device is not available
     echo "$(<"${assets_dir}/udevadm.output.${_TTY}")"

  else
     # echo "service-device-installer-tests:ERROR: unexpected udevadm query"
     /usr/bin/udevadm "$@" # passthough to real udevadm
     return 1
  fi
  return 0
}

###############################################################################
# Tests below
###############################################################################


# tests loading the serial-device-installer.conf.schema file
test_serial_device_installer_schema() {
  (($IGNORE_CONF_LIB==1)) && return 0

  # Arrange
  schema_file="$assets_dir/serial-device-installer.test1.conf.schema"

  # Act
  conf_lib_lint "$schema_file"

  # Assert
  assert_exitcode

}

test_load_with_schema_fails_missing_required_vars() {
  (($IGNORE_CONF_LIB==1)) && return 0
  # Arrange
  stage_files "serial-device-installer.test1.conf.schema" # only copy schema

  conf_file="$output_dir/serial-device-installer.test1.conf"
  assert_file_not_exist "$conf_file" $silent
  assert_file_exists "${conf_file}.schema" $silent

  local stderr=
  exec 3>&1

  # Act
  stderr="$(conf_lib_load_with_schema "$conf_file" 2>&1 1>&3)"

  #Assert
  assert_exitcode 1 "Missing Required Values"
  assert_eq "Missing required value for '\$DEVICE_SERVICE_NAME'" "${stderr}" "stderr correct"

  local var_set=false
  [[ -v "DEVICE_SERVICE_NAME" ]] && var_set=true
  assert_eq false "$var_set" "DEVICE_SERVICE_NAME is unset"

}

test_load_with_schema_succeeds_required_vars_provided() {
  (($IGNORE_CONF_LIB==1)) && return 0
  # Arrange
  stage_files "serial-device-installer.test1.conf.schema" # only copy schema

  conf_file="$output_dir/serial-device-installer.test1.conf"
  assert_file_not_exist "$conf_file" $silent
  assert_file_exists "${conf_file}.schema" $silent

  local ___SERVICE_NAME=$test_SERVICE_NAME

  # Act
  conf_lib_load_with_schema "$conf_file"

  # Assert
  assert_exitcode 0 "Missing Required Values"
  assert_eq "$DEVICE_SERVICE_NAME" "$test_SERVICE_NAME"
  assert_empty "${DEVICE_SERVICE_MAPPING_NAME:-}" $silent
  assert_empty "${DEVICE_TTY-}" $silent
  assert_not_empty "$SERVICE_PATH" $silent
  assert_not_empty "$SERIAL_STARTER_START_SERVICE_PATH" $silent
  assert_not_empty "$SERIAL_STARTER_RULES_FILE" $silent
  assert_not_empty "$SERIAL_STARTER_RULES_FILE_SYMLINK" $silent
  assert_not_empty "$SERIAL_STARTER_CONFIG_FILE" $silent
  assert_not_empty "$DEVICE_UDEV_PROPS" $silent
  assert_not_empty "$USE_UDEVADM_MONITOR" $silent
 }


# test loading defaults from schema file; required vars set
test_load_with_schema_filled_required_vars() {
  (($IGNORE_CONF_LIB==1)) && return 0
  # Arrange
  stage_files "serial-device-installer.test1.conf" "serial-device-installer.test1.conf.schema"

  conf_file="$output_dir/serial-device-installer.test1.conf"

  ___SERVICE_NAME="$test_SERVICE_NAME"

  # Act
  conf_lib_load_with_schema "$conf_file"

  # Assert
  assert_exitcode 0
  assert_eq "$DEVICE_SERVICE_NAME" "$test_SERVICE_NAME" $silent
}

# test loading defaults from schema file; conf file is missing; required vars set
test_load_with_schema_succeds_and_filled_required_vars() {
  (($IGNORE_CONF_LIB==1)) && return 0
  # Arrange
  stage_files

  conf_file="$output_dir/serial-device-installer.test1.conf"

  ___SERVICE_NAME="$test_SERVICE_NAME"

  # Act
  conf_lib_load_with_schema "$conf_file"

  # Assert
  assert_exitcode 0
  assert_eq "$DEVICE_SERVICE_NAME" "$test_SERVICE_NAME" $silent
}


# test install fails when DEVICE_TTY set to unknown tty
to_update_install_succeeds_when_TTY_is_unknown_tty_updated() {

  # Arrange
  stage_default_vars
  local stderr=
  DEVICE_TTY="ttyBAD0"

  # Act
  stderr="$(serial_device_installer_install 2>&1 )"

  # Assert
  assert_exitcode 0
  assert_eq "ERROR device not found, DEVICE_TTY: $DEVICE_TTY" "$stderr"

 }


test_install_fails_when_SERIAL_STARTER_RULES_FILE_does_not_exist() {

  # Arrange
  stage_default_vars
  DEVICE_TTY=
  SERIAL_STARTER_RULES_FILE=":@#aaa" #dummy (short) filename that will def not exist

  local stderr=

  # Act
  stderr="$(serial_device_installer_install 2>&1 )"

  #Assert
  assert_exitcode 1
  #echo "stderr:$stderr"
  assert_eq "ERROR: file not found, SERIAL_STARTER_RULES_FILE:${SERIAL_STARTER_RULES_FILE}" "$stderr"

}

test_install_fails_when_SERIAL_STARTER_CONFIG_FILE_does_not_exist() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_RULES_FILE##*/}"

  DEVICE_TTY=
  local stderr=
  SERIAL_STARTER_CONFIG_FILE=":@#aaa" #dummy (short) filename that will def not exist

  assert_file_exists "$SERIAL_STARTER_RULES_FILE"

  # Act
  stderr="$(serial_device_installer_install 2>&1)"

  #Assert
  assert_exitcode 1
  #echo "stderr:$stderr"
  assert_eq "ERROR: file not found, SERIAL_STARTER_CONFIG_FILE:$SERIAL_STARTER_CONFIG_FILE" "$stderr"

}


test_install_fails_when_UDEVADM_PROPS_is_empty() {

  # Arrange
  stage_default_vars
  DEVICE_TTY=ttyUSB0
  USB_TIMEOUT=1
  DEVICE_UDEV_PROPS=
  local stderr=

  # Act
  stderr="$(serial_device_installer_install 2>&1 )"

  #Assert
  assert_exitcode 1
  assert_eq "ERROR: DEVICE_UDEV_PROPS not set" "$stderr"
}

test_install_fails_when_UDEVADM_are_invalid() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_TTY=ttyUSB0
  DEVICE_UDEV_PROPS="BAD-PROP=1"
  local stderr=

  # Act
  stderr="$(serial_device_installer_install 2>&1)"

  #Assert
  assert_exitcode 1
  #echo "stderr:$stderr"

  assert_eq "DEVICE_UDEV_PROPS are invalid" "$stderr"

}

test_install_fails_when_SERVICE_NAME_is_empty() {

  # Arrange
  stage_default_vars
  DEVICE_SERVICE_NAME=
  local stderr=

  # Act
  stderr="$(serial_device_installer_install 2>&1)"

  #Assert
  assert_exitcode 1
  assert_eq "ERROR 1: DEVICE_SERVICE_NAME not set" "$stderr"

}

oldtest_install_SERVICE_MAPPING_NAME_set_if_empty() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SERVICE_MAPPING_NAME=
  DEVICE_TTY=ttyUSB0
  DEVICE_UDEV_PROPS="BAD_PROP=||BAD_PROP2=||" # use BAD_PROP to exit early
  local stderr=

  # Act
  serial_device_installer_install 2>/dev/null # ignore error

  #Assert
  assert_exitcode 1
  assert_empty "${DEVICE_SERVICE_MAPPING_NAME}"
}



test_install_succeeds_serial_starter_rule_added() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  local expected_serial_starter_rule_header expected_serial_starter_rule
  stage_get_expected_serial_starter_header_and_rule expected_serial_starter_rule_header expected_serial_starter_rule

  local stderr=

  # Act
  serial_device_installer_install 2>/dev/null

  #Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '# sid:ef2d: dummy_service' "$SERIAL_STARTER_RULES_FILE" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c 'ENV{SERIAL_DEVICE_ID}="ef2d"' "$SERIAL_STARTER_RULES_FILE" || true)
  assert_eq 1 "$count_of"

}

test_install_succeeds_ve_service_mapping_added() {

  # Arrange
  stage_default_vars

  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS
  local expected_ve_service_mapping; stage_get_expected_ve_service_mapping expected_ve_service_mapping
  local stderr=


  # Act
  serial_device_installer_install #2>/dev/null

  #Assert
  assert_exitcode 0

  local count_of=
  count_of=$(grep -Ec '^service[[:space:]]+ve_dummy_service[[:space:]]+dummy_service$' "$SERIAL_STARTER_CONFIG_FILE" || true)
  assert_eq 1 "$count_of"

}

test_install_succeeds_and_ve_mapping_not_added_twice_when_already_exists() {

  # Arrange
  stage_default_vars
  SERIAL_STARTER_CONFIG_FILE="${SERIAL_STARTER_CONFIG_FILE}.filled"
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS
  local expected_ve_service_mapping; stage_get_expected_ve_service_mapping expected_ve_service_mapping

  local stderr=

  # Act
  serial_device_installer_install #2>/dev/null

  #Assert
  assert_exitcode 0

  local count_of=;count_of=$(grep -o "$expected_ve_service_mapping" "${SERIAL_STARTER_CONFIG_FILE}" | wc -l)
  assert_eq 1 "${count_of}"

}

test_install_succeeds_serial_starter_rule_not_added_twice_when_already_exists() {

  # Arrange
  stage_default_vars
  SERIAL_STARTER_RULES_FILE="${SERIAL_STARTER_RULES_FILE}.filled"
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS
  local expected_serial_starter_rule_header expected_serial_starter_rule
  stage_get_expected_serial_starter_header_and_rule expected_serial_starter_rule_header expected_serial_starter_rule

  local stderr=

  # Act
  serial_device_installer_install #2>/dev/null

  #Assert
  assert_exitcode 0

  local count_of=
  count_of=$(grep -c '# sid:ef2d: dummy_service' "${SERIAL_STARTER_RULES_FILE}" || true)
  assert_eq 1 "${count_of}"
  count_of=$(grep -c 'ENV{SERIAL_DEVICE_ID}="ef2d"' "${SERIAL_STARTER_RULES_FILE}" || true)
  assert_eq 1 "${count_of}"
}

test_install_creates_rules_symlink_when_missing() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  rm -f "${SERIAL_STARTER_RULES_FILE_SYMLINK}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  # Act
  serial_device_installer_install

  # Assert
  assert_exitcode 0
  local link_target=
  link_target="$(readlink "${SERIAL_STARTER_RULES_FILE_SYMLINK}")"
  assert_eq "${SERIAL_STARTER_RULES_FILE}" "${link_target}"
}

test_install_repairs_rules_symlink_when_target_is_wrong() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  local wrong_target="${output_dir}/wrong.rules"
  : > "${wrong_target}"
  ln -sfn "${wrong_target}" "${SERIAL_STARTER_RULES_FILE_SYMLINK}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  # Act
  serial_device_installer_install

  # Assert
  assert_exitcode 0
  local link_target=
  link_target="$(readlink "${SERIAL_STARTER_RULES_FILE_SYMLINK}")"
  assert_eq "${SERIAL_STARTER_RULES_FILE}" "${link_target}"
}

test_install_fails_when_rules_symlink_path_is_regular_file() {

  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  : > "${SERIAL_STARTER_RULES_FILE_SYMLINK}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS
  local stderr=

  # Act
  stderr="$(serial_device_installer_install 2>&1)"

  # Assert
  assert_exitcode 1
  assert_eq "ERROR: SERIAL_STARTER_RULES_FILE_SYMLINK exists and is not a symlink:${SERIAL_STARTER_RULES_FILE_SYMLINK}" "${stderr}"
}

# serial_device_installer_remove

test_remove_rule_succeeds_when_sid_set_removes_comment_and_rule_line() {

  # Arrange
  stage_default_vars
  cat >"${SERIAL_STARTER_RULES_FILE}" <<'EOF'
# keep: unrelated
ACTION=="add", ENV{ID_BUS}=="usb", ENV{ID_SERIAL}=="KEEP", ENV{VE_SERVICE}="ve_keep"
# # sid:abc123: dummy_service
ACTION=="add", ENV{ID_BUS}=="usb", ENV{SERIAL_DEVICE_ID}="abc123", ENV{ID_SERIAL}=="REMOVE", ENV{VE_SERVICE}="ve_remove"
# keep: unrelated 2
ACTION=="add", ENV{ID_BUS}=="usb", ENV{ID_SERIAL}=="KEEP2", ENV{VE_SERVICE}="ve_keep2"
EOF

  DEVICE_SID="abc123"

  local stderr=

  # Act
  stderr="$(serial_device_installer_remove_rule 2>&1)"

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '^# sid:abc123:' "${SERIAL_STARTER_RULES_FILE}")
  assert_eq 0 "$count_of"

  count_of=$(grep -c 'ENV{SERIAL_DEVICE_ID}="abc123"' "${SERIAL_STARTER_RULES_FILE}")
  assert_eq 0 "$count_of"

  count_of=$(grep -c 'ENV{ID_SERIAL}=="KEEP"' "${SERIAL_STARTER_RULES_FILE}")
  assert_eq 1 "$count_of"

  count_of=$(grep -c 'ENV{ID_SERIAL}=="KEEP2"' "${SERIAL_STARTER_RULES_FILE}")
  assert_eq 1 "$count_of"
  assert_empty "$stderr"
}

test_remove_rule_succeeds_when_sid_id_not_found_file_unchanged() {

  # Arrange
  stage_default_vars
  cat >"${SERIAL_STARTER_RULES_FILE}" <<'EOF'
# keep: unrelated
ACTION=="add", ENV{ID_BUS}=="usb", ENV{ID_SERIAL}=="KEEP", ENV{VE_SERVICE}="ve_keep"
# sid:other-id: dummy_service
ACTION=="add", ENV{ID_BUS}=="usb", ENV{SERIAL_DEVICE_ID}="other-id", ENV{ID_SERIAL}=="OTHER", ENV{VE_SERVICE}="ve_other"
EOF

  cp "${SERIAL_STARTER_RULES_FILE}" "${SERIAL_STARTER_RULES_FILE}.orig"
  DEVICE_SID="abc123"

  local stderr=

  # Act
  stderr="$(serial_device_installer_remove_rule 2>&1)"

  # Assert
  assert_exitcode 0
  assert_files_eq "${SERIAL_STARTER_RULES_FILE}" "${SERIAL_STARTER_RULES_FILE}.orig"
  assert_empty "$stderr"
}


oldtest_remove_succeeds_when_serial_starter_rule_not_set() {

  # Arrange
  stage_default_vars
  SERIAL_STARTER_RULES_FILE="${SERIAL_STARTER_RULES_FILE}.filled"
  stage_files "${SERIAL_STARTER_RULES_FILE##*/}"

  local stderr=

  # Act
  stderr="$(serial_device_installer_remove 2>&1)"

  #Assert
  assert_exitcode 0

  # SERIAL_STARTER_RULE is empty rule not removed
  local rule_added="# \"dummy_service\""
  local count_of=;count_of=$(grep -o "$rule_added" "${SERIAL_STARTER_RULES_FILE}" | wc -l)
  assert_eq "SERIAL_STARTER_RULE not set, nothing to do" "$stderr"

}

oldtest_remove_succeeds_when_serial_starter_rule_set() {

   # Arrange
  stage_default_vars
  SERIAL_STARTER_RULES_FILE="${SERIAL_STARTER_RULES_FILE}.filled"
  stage_files "${SERIAL_STARTER_RULES_FILE##*/}"
  local serial_starter_rule_header serial_starter_rule_code
  stage_get_expected_serial_starter_header_and_rule serial_starter_rule_header serial_starter_rule_code

  local stderr=
  local count_of=

  count_of=$(grep -o "$serial_starter_rule_header" "${SERIAL_STARTER_RULES_FILE}" | wc -l)
  assert_eq 1 "$count_of" "--"

  count_of=$(grep -o "$serial_starter_rule_code" "${SERIAL_STARTER_RULES_FILE}" | wc -l)
  assert_eq 1 "$count_of" "--"

  # Act
  stderr=$(serial_device_installer_remove) #2>/dev/null

  #Assert
  assert_exitcode 0

  local count_of=
  count_of=$(grep -o "$serial_starter_rule_header" "${SERIAL_STARTER_RULES_FILE}" | wc -l)
  assert_eq 0 "$count_of"

  count_of=$(grep -o "$serial_starter_rule_code" "${SERIAL_STARTER_RULES_FILE}" | wc -l)
  assert_eq 0 "$count_of"

  assert_empty $stderr
}


test_remove_succeeds_SERIAL_STARTER_CONF_entry_is_removed() {

   # Arrange
  stage_default_vars
  SERIAL_STARTER_RULES_FILE="${SERIAL_STARTER_RULES_FILE}.filled"
  SERIAL_STARTER_CONFIG_FILE="${SERIAL_STARTER_CONFIG_FILE}.filled"

  stage_files "${SERIAL_STARTER_RULES_FILE##*/}" "${SERIAL_STARTER_CONFIG_FILE##*/}"
  local expected_ve_service_mapping; stage_get_expected_ve_service_mapping expected_ve_service_mapping
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  _TTY=ttyUSB0
  local stderr=
  local count_of=
  count_of=$(grep -o "$expected_ve_service_mapping" "${SERIAL_STARTER_CONFIG_FILE}" | wc -l)
  assert_eq 1 "$count_of" "--"

  # Act
  #serial_device_installer_remove
  stderr=$(serial_device_installer_remove_service_mapping) #2>/dev/null

  #Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  local line_no=;line_no=$(awk "/${expected_ve_service_mapping}/{ print NR; exit }" "$SERIAL_STARTER_CONFIG_FILE")
  assert_empty "${line_no}"
}

test_remove_succeeds_config_file_remains_unchanged_when_ve_service_mapping_not_found() {

   # Arrange
  stage_default_vars
  SERIAL_STARTER_RULES_FILE="${SERIAL_STARTER_RULES_FILE}.filled"
  SERIAL_STARTER_CONFIG_FILE="${SERIAL_STARTER_CONFIG_FILE}.filled"

  stage_files "${SERIAL_STARTER_RULES_FILE##*/}" "${SERIAL_STARTER_CONFIG_FILE##*/}"
  local serial_starter_rule_header serial_starter_rule_code
  stage_get_expected_serial_starter_header_and_rule serial_starter_rule_header serial_starter_rule_code

  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  local stderr=
  local count_of=

  DEVICE_SERVICE_NAME="ve_some_other_service" # set to any value other than 'service ve_dummy_service'
  local service_added="service ve_dummy_service ve_some_other_service"

  cp "${SERIAL_STARTER_CONFIG_FILE}" "${SERIAL_STARTER_CONFIG_FILE}.orig"
  count_of=$(grep -o "$service_added" "${SERIAL_STARTER_CONFIG_FILE}" | wc -l)
  assert_eq 0 "$count_of" "--"

  # Act
  stderr=$(serial_device_installer_remove_service_mapping) #2>/dev/null

  #Assert
  assert_exitcode 0
  #echo "stderr:$stderr"

  local line_no=;line_no=$(awk "/${service_added}/{ print NR; exit }" "$SERIAL_STARTER_CONFIG_FILE")

  # nothing removed files remain unchanged
  assert_files_eq "$SERIAL_STARTER_CONFIG_FILE" "${SERIAL_STARTER_CONFIG_FILE}.orig"

  assert_empty $stderr
}

test_start_service_fails_when_tty_not_found() {

  # Arrange
  stage_default_vars
  stage_service_paths
  stage_get_filled_UDEVADM_PROPS_no_match DEVICE_UDEV_PROPS

  local stderr=

  # Act

  stderr="$(serial_device_installer_start_service 2>&1)"

  # Assert
  assert_exitcode 1
  assert_eq "ERROR: DEVICE_TTY device does not exist" "${stderr}"
}


test_start_service_fails_when_SERIAL_STARTER_START_SERVICE_PATH_not_set() {

  # Arrange
  stage_default_vars
  stage_service_paths
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  SERIAL_STARTER_START_SERVICE_PATH=

  local stderr=

  # Act
  stderr="$(serial_device_installer_start_service 2>&1)"

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"
  assert_eq "ERROR: SERIAL_STARTER_START_SERVICE_PATH not set or does not exist" "${stderr}"
}

test_start_service_fails_when_SERVICE_NAME_not_set() {

  # Arrange
  stage_default_vars
  stage_service_paths
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  DEVICE_SERVICE_NAME=

  local stderr=

  # Act
  stderr="$(serial_device_installer_start_service 2>&1)"

  # Assert
  assert_exitcode 1
  #echo "stderr:$stderr"
  assert_eq "ERROR 2: DEVICE_SERVICE_NAME not set" "${stderr}"
}

TTY_EXISTS=
__tty_device_exists() {
  [[ -n $TTY_EXISTS ]] && return $TTY_EXISTS
  [[ -e "/dev/${1}" ]]
}

test_start_service_succeeds_when_all_conditions_are_met() {

  # Arrange
  stage_default_vars
  stage_service_paths
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS
  DEVICE_TTY=ttyUSB0
  TTY_EXISTS=0 # use dummy __tty_device_exists function above

  local stderr=

  # Act
  stderr="$(serial_device_installer_start_service 2>&1)"
  TTY_EXISTS=

  # Assert
  assert_exitcode 0
  [[ -n $stderr ]] && echo "stderr:$stderr"
  assert_file_exists "${SERIAL_STARTER_START_SERVICE_PATH}/ttyUSB0"

} #check auto tty file exists

test_uninstall_uses_service_path_variable() {
  # Arrange
  stage_default_vars
  stage_service_paths

  local -a seen_services=()
  __serial_device_installer_remove_service() {
    seen_services+=("$1")
  }

  DEVICE_SERVICE_NAME="dummy_service"
  mkdir -p "${SERVICE_PATH}/${DEVICE_SERVICE_NAME}.ttyUSB0"
  mkdir -p "${SERVICE_PATH}/${DEVICE_SERVICE_NAME}.ttyACM0"

  # Act
  serial_device_installer_uninstall --no-remove-usb-rule --no-remove-service-mapping

  # Assert
  assert_exitcode 0
  assert_eq 2 "${#seen_services[@]}"
  assert_eq "dummy_service.ttyACM0" "${seen_services[0]}"
  assert_eq "dummy_service.ttyUSB0" "${seen_services[1]}"
}

test_remove_rule_with_sid_removes_only_matching_rule() {
  # Arrange
  stage_default_vars
  cat >"${SERIAL_STARTER_RULES_FILE}" <<'EOF'
# sid:abcd: dummy_service
ACTION=="add", ENV{ID_BUS}=="usb", ENV{SERIAL_DEVICE_ID}="abcd", ENV{VE_SERVICE}="ve_dummy_service"
ACTION=="add", ENV{ID_BUS}=="usb", ENV{SERIAL_DEVICE_ID}="efef", ENV{VE_SERVICE}="ve_other"
EOF

  DEVICE_SID="abcd"

  # Act
  serial_device_installer_remove_rule

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c 'abcd' "${SERIAL_STARTER_RULES_FILE}" || true)
  assert_eq 0 "$count_of"
  count_of=$(grep -c 'efef' "${SERIAL_STARTER_RULES_FILE}" || true)
  assert_eq 1 "$count_of"
}

test_install_from_sid_fails_without_tty() {
  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  local stderr=

  # Act
  stderr="$(serial_device_installer_install_from_sid 2>&1)"

  # Assert
  assert_exitcode 1
  assert_eq "ERROR: DEVICE_TTY must be set to an existing device for DEVICE_SID install" "$stderr"
}

test_install_from_sid_succeeds_with_tty_and_props() {
  # Arrange
  stage_default_vars
  stage_files "${SERIAL_STARTER_CONFIG_FILE##*/}" "${SERIAL_STARTER_RULES_FILE##*/}"
  DEVICE_SID=ef2d
  DEVICE_TTY=tty
  stage_get_filled_UDEVADM_PROPS DEVICE_UDEV_PROPS

  local stderr=

  # Act
  stderr="$(serial_device_installer_install_from_sid 2>&1)"

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c 'ENV{SERIAL_DEVICE_ID}="ef2d"' "${SERIAL_STARTER_RULES_FILE}" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -Ec '^service[[:space:]]+ve_dummy_service[[:space:]]+dummy_service$' "${SERIAL_STARTER_CONFIG_FILE}" || true)
  assert_eq 1 "$count_of"
  assert_eq "    fake-svc called with args:-t /service/serial-starter" "$stderr"
}

test_uninstall_wrapper_calls_package_uninstall() {
  # Arrange
  local called=
  serial_device_installer_uninstall_package() {
    called=1
    return 0
  }

  # Act
  serial_device_installer_uninstall --no-remove-usb-rule

  # Assert
  assert_exitcode 0
  assert_eq 1 "$called"
}

test_uninstall_package_removes_rules_symlink() {
  # Arrange
  stage_default_vars
  local rules_file="${SERIAL_STARTER_RULES_FILE}"
  local rules_link="${SERIAL_STARTER_RULES_FILE_SYMLINK}"
  : > "${rules_file}"
  ln -sfn "${rules_file}" "${rules_link}"

  # Act
  serial_device_installer_uninstall_package --no-remove-usb-rule --no-remove-service-mapping

  # Assert
  assert_exitcode 0
  assert_file_not_exist "${rules_link}"
}

test_remove_device_rule_calls_rule_and_refresh() {
  # Arrange
  stage_default_vars
  DEVICE_SID="abcd"
  DEVICE_TTY="ttyUSB0"
  local calls_file="${output_dir}/phase5.calls"
  : > "$calls_file"

  serial_device_installer_remove_rule() {
    echo "remove_rule" >> "$calls_file"
    return 0
  }
  __ensure_TTY_from_TTY_or_SID() {
    return 0
  }
  serial_device_installer_refresh_udevadm() {
    echo "refresh:${1}" >> "$calls_file"
    return 0
  }

  # Act
  serial_device_installer_remove_device_rule

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '^remove_rule$' "$calls_file" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c '^refresh:remove$' "$calls_file" || true)
  assert_eq 1 "$count_of"
}

test_install_common_uses_uninstall_package_api() {
  # Arrange
  local helper_file="$this_path/../src/data/opkg-manager/installer-common"
  local count_of=

  # Act / Assert
  count_of=$(grep -c 'serial_device_installer_uninstall_package' "$helper_file" || true)
  assert_eq 1 "$count_of"
}

test_device_remove_uses_remove_device_rule_api() {
  # Arrange
  local device_file="$this_path/../src/data/opkg-manager/opkg-bridge/device"
  local count_of=

  # Act / Assert
  count_of=$(grep -c 'serial_device_installer_remove_device_rule' "$device_file" || true)
  assert_eq 1 "$count_of"
}

test_device_apply_uses_install_from_sid_api() {
  # Arrange
  local device_file="$this_path/../src/data/opkg-manager/opkg-bridge/device"
  local count_of=

  # Act / Assert
  count_of=$(grep -c 'serial_device_installer_install_from_sid' "$device_file" || true)
  assert_eq 1 "$count_of"
}

test_restart_services_finds_matching_tty_by_ve_service() {
  # Arrange
  stage_default_vars
  stage_service_paths

  local tty0="${output_dir}/sys/class/tty/ttyUSB0"
  local tty1="${output_dir}/sys/class/tty/ttyACM0"
  mkdir -p "${tty0%/*}" "${tty1%/*}"
  : > "$tty0"
  : > "$tty1"

  __get_tty_paths() {
    local -n _out=$1
    _out=("$tty0" "$tty1")
  }

  serial_device_installer_get_usb_prop() {
    local tty="$1"
    local key="$2"
    [[ "$key" == "VE_SERVICE" ]] || return 0
    echo "ve_dummy_service"
  }

  mkdir -p "/var/lock/serial-starter"
  : > "/var/lock/serial-starter/ttyUSB0"
  rm -f "${SERIAL_STARTER_START_SERVICE_PATH}/ttyUSB0" "${SERIAL_STARTER_START_SERVICE_PATH}/ttyACM0"

  # Act
  serial_device_installer_restart_services

  # Assert
  assert_exitcode 0
  assert_file_not_exist "${SERIAL_STARTER_START_SERVICE_PATH}/ttyUSB0"
  assert_file_exists "${SERIAL_STARTER_START_SERVICE_PATH}/ttyACM0"
}

test_restart_services_skips_non_matching_services() {
  # Arrange
  stage_default_vars
  stage_service_paths

  local tty0="${output_dir}/sys/class/tty/ttyUSB0"
  local tty1="${output_dir}/sys/class/tty/ttyACM0"
  mkdir -p "${tty0%/*}" "${tty1%/*}"
  : > "$tty0"
  : > "$tty1"

  __get_tty_paths() {
    local -n _out=$1
    _out=("$tty0" "$tty1")
  }

  serial_device_installer_get_usb_prop() {
    local tty="$1"
    local key="$2"
    [[ "$key" == "VE_SERVICE" ]] || return 0
    [[ "$tty" == "ttyUSB0" ]] && echo "ve_dummy_service"
    [[ "$tty" == "ttyACM0" ]] && echo "ve_other"
  }

  mkdir -p "/var/lock/serial-starter"
  rm -f "/var/lock/serial-starter/ttyUSB0" "/var/lock/serial-starter/ttyACM0"
  rm -f "${SERIAL_STARTER_START_SERVICE_PATH}/ttyUSB0" "${SERIAL_STARTER_START_SERVICE_PATH}/ttyACM0"

  # Act
  serial_device_installer_restart_services

  # Assert
  assert_exitcode 0
  assert_file_exists "${SERIAL_STARTER_START_SERVICE_PATH}/ttyUSB0"
  assert_file_not_exist "${SERIAL_STARTER_START_SERVICE_PATH}/ttyACM0"
}

test_reload_serial_starter_service_calls_svc_t_when_up() {
  # Arrange
  local calls_file="${output_dir}/reload.calls"
  : > "$calls_file"

  svstat() {
    echo "serial-starter: up (pid 1)"
  }

  svc() {
    echo "$*" >> "$calls_file"
  }

  # Act
  serial_device_installer_reload_serial_starter_service

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '^-t /service/serial-starter$' "$calls_file" || true)
  assert_eq 1 "$count_of"
}

test_reload_serial_starter_service_calls_svc_u_when_down() {
  # Arrange
  local calls_file="${output_dir}/reload.calls"
  : > "$calls_file"

  svstat() {
    echo "serial-starter: down (pid 1)"
  }

  svc() {
    echo "$*" >> "$calls_file"
  }

  # Act
  serial_device_installer_reload_serial_starter_service

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '^-u /service/serial-starter$' "$calls_file" || true)
  assert_eq 1 "$count_of"
}

test_tty_from_sid_sets_tty_when_found() {
  # Arrange
  DEVICE_SID="ef2d"
  DEVICE_TTY=

  __get_tty_from_props_byref() {
    local -n _props="${1}"
    local -n out_tty="${2}"
    [[ "${_props[SERIAL_DEVICE_ID]:-}" == "ef2d" ]] || return 1
    out_tty="ttyUSB9"
    return 0
  }

  # Act
  serial_device_installer_TTY_from_SID

  # Assert
  assert_exitcode 0
  assert_eq "ttyUSB9" "$DEVICE_TTY"
}

test_tty_from_sid_returns_failure_when_not_found() {
  # Arrange
  DEVICE_SID="bad1"
  DEVICE_TTY=

  __get_tty_from_props_byref() {
    return 1
  }

  # Act
  serial_device_installer_TTY_from_SID

  # Assert
  assert_exitcode 1
  assert_empty "${DEVICE_TTY:-}"
}

test_stop_service_tree_noop_when_missing_dir() {
  # Arrange
  local missing_dir="${output_dir}/no-such-service"

  # Act
  __stop_service_tree "$missing_dir"

  # Assert
  assert_exitcode 0
  assert_file_not_exist "${missing_dir}/down"
}

test_stop_service_tree_creates_down_files_and_calls_svc() {
  # Arrange
  local service_dir="${output_dir}/service-tree/dummy.ttyUSB0"
  local calls_file="${output_dir}/stop-tree.calls"
  mkdir -p "${service_dir}/log"
  : > "$calls_file"

  svc() {
    echo "$*" >> "$calls_file"
  }

  # Act
  __stop_service_tree "$service_dir"

  # Assert
  assert_exitcode 0
  assert_file_exists "${service_dir}/down"
  assert_file_exists "${service_dir}/log/down"
  local count_of=
  count_of=$(grep -c "^-d ${service_dir}$" "$calls_file" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c "^-x ${service_dir}$" "$calls_file" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c "^-d ${service_dir}/log$" "$calls_file" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c "^-x ${service_dir}/log$" "$calls_file" || true)
  assert_eq 1 "$count_of"
}

test_kill_leftover_processes_noop_when_no_pids() {
  # Arrange
  local calls_file="${output_dir}/kill.calls"
  : > "$calls_file"

  pgrep() {
    return 1
  }

  kill() {
    echo "$*" >> "$calls_file"
    return 0
  }

  # Act
  __kill_leftover_service_processes "dummy_service.ttyUSB0"

  # Assert
  assert_exitcode 0
  local lines=
  lines=$(wc -l < "$calls_file")
  assert_eq 0 "$lines"
}

test_kill_leftover_processes_calls_kill_and_kill9_when_pids_found() {
  # Arrange
  local calls_file="${output_dir}/kill.calls"
  : > "$calls_file"

  pgrep() {
    echo "$$"
    echo "123"
    echo "456"
  }

  kill() {
    echo "$*" >> "$calls_file"
    return 0
  }

  sleep() {
    return 0
  }

  # Act
  __kill_leftover_service_processes "dummy_service.ttyUSB0"

  # Assert
  assert_exitcode 0
  local count_of=
  count_of=$(grep -c '^123 456$' "$calls_file" || true)
  assert_eq 1 "$count_of"
  count_of=$(grep -c '^-9 123 456$' "$calls_file" || true)
  assert_eq 1 "$count_of"
}

test_get_usb_prop_returns_value_when_present() {
  # Arrange
  udevadm() {
    [[ "$1" == "info" ]] || return 1
    cat <<'EOF'
ID_VENDOR=FTDI
ID_MODEL=FT232R_USB_UART
EOF
  }

  local out=

  # Act
  out="$(serial_device_installer_get_usb_prop "ttyUSB0" "ID_VENDOR")"

  # Assert
  assert_exitcode 0
  assert_eq "FTDI" "$out"
}

test_get_usb_prop_returns_empty_when_missing() {
  # Arrange
  udevadm() {
    [[ "$1" == "info" ]] || return 1
    cat <<'EOF'
ID_VENDOR=FTDI
ID_MODEL=FT232R_USB_UART
EOF
  }

  local out=

  # Act
  out="$(serial_device_installer_get_usb_prop "ttyUSB0" "ID_SERIAL")"

  # Assert
  assert_exitcode 0
  assert_empty "$out"
}

test_prepare_props_for_grep_escapes_plus_keys() {
  # Arrange
  local -A props
  props["+ID_SERIAL"]="abc"
  props["ID_VENDOR"]="FTDI"
  local out=

  # Act
  __prepare_props_for_grep_byref props out

  # Assert
  assert_not_empty "$out"
  local has_plus=false
  local has_vendor=false
  [[ "$out" == *"\\+ID_SERIAL="* ]] && has_plus=true
  [[ "$out" == *"ID_VENDOR="* ]] && has_vendor=true
  assert_eq true "$has_plus"
  assert_eq true "$has_vendor"
}

test_props_roundtrip_read_write_preserves_key_values() {
  # Arrange
  DEVICE_UDEV_PROPS='ID_MODEL=FT232R_USB_UART,ID_SERIAL=FTDI_ABC,+SERIAL_DEVICE_ID=ef2d,ID_VENDOR=FTDI'
  local -A props1
  local -A props2

  # Act
  __read_props_byref props1
  assert_exitcode 0
  __write_props props1
  __read_props_byref props2

  # Assert
  assert_exitcode 0
  assert_eq "${#props1[@]}" "${#props2[@]}"
  local key=
  for key in "${!props1[@]}"; do
    assert_eq "${props1[$key]}" "${props2[$key]:-}"
  done
}

pre_test_runner() {
  clear_output
  stage_reset_vars
}
post_test_runner() {
true
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then
  #clear
  #test_install_fails_when_UDEVADM_are_invalid
  #exit
  clear_output

  #declare cur_func; cur_func=$(grep -E '^cur_test_[^[:space:]]*\(\).*' "${BASH_SOURCE[0]}")
  #cur_func=${cur_func%%\(\)*}
  #[[ "$cur_func" ]] && { "$cur_func"; exit 0; }

  # "dummy_service"
  EXIT_ON_FAILED_TEST=1
  test_runner_all --summary "" #"^cur_test_*"
fi
