#!/usr/bin/env bash

set -o nounset

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../src/data/apps/available/vespera/libs/service-lib"

SVC_CALLS=

svc() {
  SVC_CALLS+=$'\n'"$*"
}

test_service_lib_service_up_returns_success_for_up_status() {
  svstat() {
    printf '%s: up (pid 100) 2 seconds\n' "$1"
  }

  service_lib_service_up demo
  assert_exitcode 0
}

test_service_lib_service_up_returns_failure_for_down_status() {
  svstat() {
    printf '%s: down 2 seconds\n' "$1"
  }

  service_lib_service_up demo
  assert_exitcode_not 0
}

test_service_lib_remove_service_is_noop_when_service_missing() {
  local before="$SVC_CALLS"

  service_lib_remove_service service-that-does-not-exist

  assert_exitcode 0
  assert_eq "$before" "$SVC_CALLS"
}

test_service_lib_start_templated_service_fails_for_missing_device() {
  local stderr
  stderr="$(service_lib_start_templated_service this-device-does-not-exist sample-service 2>&1)"

  assert_exitcode 1
  assert_contains 'ERROR: invalid device' "$stderr"
}

test_service_lib_start_templated_service_fails_for_unknown_service_name() {
  local stderr
  stderr="$(service_lib_start_templated_service null '' 2>&1)"

  assert_exitcode 1
  assert_contains 'ERROR: unknown service' "$stderr"
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then
  test_runner_all --summary ""
fi
