#!/usr/bin/env bash

set -o nounset

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cli_file="$this_path/../src/bin/vespera"

. "$this_path/../../../scripts/libs/test-lib"

test_vespera_cli_has_expected_shebang() {
  local first_line
  first_line="$(head -n 1 "$cli_file")"

  assert_eq '#!/bin/bash' "$first_line"
}

test_vespera_cli_execs_main_script_with_forwarded_args() {
  assert_file_contains "$cli_file" 'exec /data/apps/available/vespera/vespera "$@"'
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then
  test_runner_all --summary ""
fi
