#!/bin/env bash

BUILD_DIR=/data/dev/addons/opkg-manager/src-external/gui-v2/OpkgManager

if [[ ! -f "$HOME/dev-local/make-opkg-manager-plugin" ]]; then
	echo "opkg-manager/build: dev-local not available"
else
	cd "$BUILD_DIR" || exit

	./build-plugin # 192.168.10.24
fi
