#!/bin/bash
#
# Start script for dbus-inetbox
#   First parameter: tty device to use
#
# Keep this script running with daemon tools. If it exits because the
# connection crashes, or whatever, daemon tools will start a new one.
#
# Arguments
# -d -debug  : debug logging
# -s -serial : serial port such as ttyACM0
# -i -sid : SERIAL_DEVICE_ID value added from the serial-starter.rules file

. /opt/victronenergy/serial-starter/run-service.sh

sid=$(udevadm info --query=property --name="/dev/$tty" | sed -n "s/^SERIAL_DEVICE_ID=//p")
if [[ -z "$sid" ]]; then
	# shutdown the service so it does not continue trying to run
	# without the required sid
	echo "$product.$tty missing sid; exiting service startup from $0"
	cleanup
	pid=$$ # so term in run-service.sh has somthing to kill ;)
	svc -d .
	exit 1
fi

app=$(dirname $0)/__main__.py

start -s "/dev/$tty" -i "$sid"
