#!/usr/bin/env bash

# shellcheck disable=SC2034
LOG_LIB_VERSION=1.0
 
LOG_INDENT_CHAR=" "
LOG_INDENT=

: "${LOGGER:=1}"
: "${LOGLEVEL_NONE:=0}"
: "${LOGLEVEL_ERROR:=1}"
: "${LOGLEVEL_MINIMAL:=2}"
: "${LOGLEVEL_INFO:=3}"
: "${LOGLEVEL_TRACE:=4}"
readonly LOGGER LOGLEVEL_NONE LOGLEVEL_ERROR LOGLEVEL_MINIMAL LOGLEVEL_INFO LOGLEVEL_TRACE
 
LOGLEVEL=$LOGLEVEL_INFO
: "${LOGLEVEL:=$LOGLEVEL_INFO}"

 # source must contain a method called CUSTOM_LOGGING_FUNC
# depreciated just define a function called log_custom
#declare USE_CUSTOM_LOGGING_FUNC= 
LOG_DATE_TIME=1
LOG_FUNC_NAME=1
LOG_SOURCE_NAME=1

log_trace() { log "${1:-}" $LOGLEVEL_TRACE 2; }
log_info() { log "${1:-}" $LOGLEVEL_INFO 2; }
log_error() { log "${1:-}" $LOGLEVEL_ERROR 2; }

log() {

  #use "${@: -1}" to get the last arg incase args 1 is empty
  # [[ (( $#>1 )) ]] && [[ (($LOGLEVEL < "${2:=$LOGLEVEL_MINIMAL}")) ]] && return 0

  if (( $#>1 )); then
    local arg2=$2
    # shellcheck disable=SC2071
    ((LOGLEVEL<arg2)) && return 0
  else
    # shellcheck disable=SC2071
    ((LOGLEVEL<LOGLEVEL_MINIMAL)) && return 0
  fi

  # shellcheck disable=SC2071
  (( $# > 2 )) && func_offset=$3 || func_offset=1
  (( LOGLEVEL == LOGLEVEL_NONE )) && return 0
  
  [[ $(type -t log_custom) == function ]] && {
      local r
      log_custom; 
      r=$?
      (( r != 0 )) && return $?
  }
  local prefix=

  if (( LOGLEVEL > LOGLEVEL_INFO )); then
 
    [[ $LOG_DATE_TIME ]] && prefix="$(date +%y/%m/%d_%H:%M:%S)::"
    [[ $LOG_SOURCE_NAME ]] && prefix+="${BASH_SOURCE[func_offset]##*/}::"
    [[ $LOG_FUNC_NAME ]] && prefix+="${FUNCNAME[func_offset]}::"

    [[ -z $1 ]] && [[ -n $prefix ]] && prefix=${prefix::-2} # remove :: from end
  else
    # don't log null lines
    [[ -z $1 ]] && return 0
  fi
  
  if [[ -v "LOG_FILE" && -f "${LOG_FILE}" ]]; then
    echo "${LOG_INDENT}${prefix}${1}" >> "${LOG_FILE}"
  elif [[ ${2:-} == $LOGLEVEL_ERROR ]]; then
    echo "${LOG_INDENT}${prefix}${1}" >&2
  else
    echo "${LOG_INDENT}${prefix}${1}" >&1
  fi

return 0
}

log_pop_indent() {
  __log_set_indent $((${#LOG_INDENT}-2))
}

log_push_indent() {
  __log_set_indent $((${#LOG_INDENT}+2))
}

__log_set_indent() {

  [[ -z $LOG_INDENT_CHAR ]] && return 0

  INDENT_LEN=${1}
  LOG_INDENT=

  if [[ INDENT_LEN -gt 0 ]]; then
    for((i=0; i<INDENT_LEN; i++)); do
      LOG_INDENT="${LOG_INDENT}${LOG_INDENT_CHAR}"
    done
  fi
}

init_logging_to_file() {
  #exec &> "$1"
  LOG_FILE="$1"
  echo "*** $(date +%y/%m/%d_%H:%M:%S) ***" > "$1"
}

if [[ "${1:-}" == "init_logging" ]]; then
  echo "init_logging ${2:-}"
  echo "${2:-}"
fi
