#!/usr/bin/env bash

set -o nounset

##########################################################
# returns if the passed string is uppercase
# Arguments:
#   $1 string to query
##########################################################
string_lib_is_upper()  { [[ "$1" =~ ^[A-Z_][A-Z0-9_]*$ ]]; }

##########################################################
# returns if the passed string is lowercase
# Arguments:
#   $1 string to query
##########################################################
string_lib_is_lower()  { [[ "$1" =~ ^[a-z_][A-Z0-9_]*$ ]]; }

##########################################################
# returns if the passed string ends with a double quote
# Arguments:
#   $1 string to query
##########################################################
string_lib_ends_with_quote() { [[ $1 =~ (^|[^\\])\"$ ]]; }

##########################################################
# returns if the passed string starts with a double quote
# Arguments:
#   $1 string to query
##########################################################
string_lib_starts_with_quote() { [[ "$1" =~ (^|[^\\])\" ]]; }

##########################################################
# trims whitespace from the start of the passed string
# Arguments:
#   $1 string to trim
#      the string is passed byref 
#      string_lib_trim_start str (not $str)
##########################################################
string_lib_trim_start() {
  local -n _s="$1"
  _s="${_s#"${_s%%[![:space:]]*}"}"
}

##########################################################
# trims whitespace from the end of the passed string
# Arguments:
#   $1 string to trim
#      the string is passed byref 
#      string_lib_trim_end str (not $str)
##########################################################
string_lib_trim_end() {
  local -n _s="$1"
  _s="${_s%"${_s##*[![:space:]]}"}"
}

##########################################################
# trims whitespace from the start and of the passed string
# Arguments:
#   $1 string to trim
#      the string is passed byref 
#      string_lib_trim str (not $str)
##########################################################
string_lib_trim() {
  local -n _s="$1"
  _s="${_s#"${_s%%[![:space:]]*}"}"
  _s="${_s%"${_s##*[![:space:]]}"}"
}
 
 ##########################################################
# removes all whitespace anywhere in the passed string
# Arguments:
#   $1 string to remove whitespace from
#      the string is passed byref 
#      string_lib_remove_all_whitespace str (not $str)
##########################################################
string_lib_remove_all_whitespace() {
  local -n _s="$1"
  _s="${_s//[[:space:]]/}"
}

 ##########################################################
# unescapes quotes and backslashes from the passed string
# Arguments:
#   $1 string to unescape
#      the string is passed byref 
#      string_lib_remove_all_whitespace str (not $str)
##########################################################
string_lib_unescape() {
  local -n _s="$1"

  # First unescape escaped quotes
  _s="${_s//\\\"/\"}"

  # Then unescape escaped backslashes
  _s="${_s//\\\\/\\}"
}
 

##########################################################
# replaces newlines with \n so whole string can ve viewed 
# in debugger (and not just the first line)
# Arguments:
#   $1 string to debug
#   $2 output string (byref) 
# Usage:
# local _d=; make_debug_str "${output}" _d
##########################################################
make_debug_str() {
  local -n _out=$2
  _out="${1//$'\n'/\\n}"
  _out="${_out//$'\t'/\\t}"
  return 0
}
##########################################################
# Reads from stdout to the variable named in arg1.
# the content in stdout should be null terminated
# The variable should not be escaped or use $ in front
# incorect: $VARNAME, "${VARNAME}" etc...
# correct:  VARNAME
##########################################################
set_var() {
  local -n _out=$1
  IFS= read -r -d '' _out || :
  return 0
}
##########################################################
# sends arg1 to stdin terminated with a null 
##########################################################
send_var () {
  printf '%s\0' "${1}"
  return 0
}

##########################################################
# Finds and replaces multiline text in the string contents provided
# in STDIN. The search string can contain any characters.
# Arguments
# $1 (required): The multi-line string to find/replace
#  --break-on-first | -b : Exists when the first item is found or removed. 
#  --find-only      | -f : Find the text only. Returns the number of occurances. 
#                          If break-on-first will return 1
#                          otherwise the source string is returned with the 
#                          multiline strings removed. 
#  --trim-lines     | -t : Trims line feeds around the removed strings. 
#                          (tries to leave one space)
#  --replacement-text | optional text to replace the exiting text
#  Input: Content via STDIN '< [filename]' or '<<< [string]' to supply the contents
#  Returns: The modified string or the number of matches depending on the options above
##########################################################
string_lib_multiline_find_replace() {

_printhelp() {
  cat <<EOF
Searches for a multiline string in the stdin.
 
  Version 1.1

  Named Arguments:
  --break-on-first     | -b : Exists when the first item is found or removed.
  --find-only          | -f : Find the text only. Returns the number of occurances. 
                            If break-on-first will return 1
                            otherwise the source string is returned with the 
                            multiline strings removed.
  --trim-lines         | -t : Trims line feeds around the removed strings. 
                            It will attempt to leave one space)
  --ignore-white-space | ignores white space (spaces tabs etc.) and the start and
                            end of a line when matching
  --replacement-text   | -r : optional text to replace the exiting text


  The first none argument string must be the string to find
  The optional second argument string is the file name of the string to search in
  In the file name is not used then stdin is used
  Input can also be via STDIN '< [filename]' or '<<< [string]' to supply the contents
  note:HereDoc (<<<) appends an extra linefeed char to the end 
  Returns: The modified string or the number of matches depending on the options above

EOF
}
 
  if [[ "$1" == "--help" ]]; then
    _printhelp; return 0
  fi
 
  local -i pat_len=0; local -i idx_pat=0
  local -i match_start=-1; local -i found=0
  local -i opt_break_on_first=0; local -i opt_find_only=0
  local -i opt_trim_lines=0; local -i trim_forward_newlines=0
  local opt_replacement_text=; local opt_ignore_white_space=0
  local -i matched_line=0
  local newline=$'\n'
  local output=
  local search_string=
  local pat_lines=()
  local filename=
  local trimmed=

  # process args
  while [ $# -gt 0 ]; do
    case "$1" in
      --break-on-first*|-b*) opt_break_on_first=1 ;;
      --find-only*|-f*) opt_find_only=1 ;;
      --trim-lines*|-t*) opt_trim_lines=1 ;;
      --ignore-white-space*|-w*) opt_ignore_white_space=1 ;;
      --replacement-text*|-r*)
        if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
        opt_replacement_text="${1#*=}" ;;
        
      --help|-h) _printhelp; return 0 ;;
      *)
        if [[ -z "$search_string" ]]; then
          search_string="$1"
        elif [[ -z "$filename" ]]; then
          if [[ -f "$1" ]] ; then
            filename="$1"
          else
            printf "%s :Error: File '%s' not found\n" "${FUNCNAME[0]}" "${1}"
            return 1
          fi
        else
          >&2 printf "%s :Error: Invalid argument\n" "${FUNCNAME[0]}"
          return 1
        fi
        ;;
  
    esac
    shift
  done

  [[ -z "$search_string" ]] && { printf "%s :Error: No search string provided" "${FUNCNAME[0]}"; return 1; }
 
  IFS=$'\n' read -d '' -r -a pat_lines <<< "$search_string" || :
  pat_len=${#pat_lines[@]}

  # shellcheck disable=SC2329,SC2317
  cleanup() {
    if [[ $saved_fd ]]; then
      exec 0<&"$saved_fd"
      exec {saved_fd}<&-
    fi
  }

  if [[ -n "$filename" ]] ; then #already checked if file exists
    exec {saved_fd}<&0 # requires bash 4 min
    trap 'cleanup' RETURN
  fi 

  ########################################################

  # for debugging
  #for pline in "${pat_lines[@]}"; do echo "$idx_pat:$pline"; idx_pat+=1; done
  # idx_pat=0
  
  # Make sure we read the last line even when the input string 
  # does not contain a final return
  # read returns an error if no line return is found.
  # we catch that error and continue if $line is not empty. 
  # if [ -n "$line" ] is true; We also set newline=''
  # So we don't output an extra newline and our output string 
  # exactly matches the input string (minus any trimming/replacements).

  while IFS= read -r line || { [ -n "$line" ] && newline=''; } do
    if (( trim_forward_newlines == 1 )) then
      [[ -z "${line// }" ]] && continue
      trim_forward_newlines=0
    fi

    matched_line=0
    if (( found == 0 || opt_break_on_first != 1 )); then
      if (( opt_ignore_white_space == 0 )); then
        [[ "${pat_lines[$idx_pat]}" == "$line" ]] && matched_line=1
      else
        trimmed="${line#"${line%%[![:space:]]*}"}" # trim leading whitespace
        trimmed="${trimmed%"${trimmed##*[![:space:]]}"}" # trim trailing whitespace
        [[ "$trimmed" == "${pat_lines[$idx_pat]}"  ]] && matched_line=1
      fi
    fi

    if (( matched_line == 1 )); then

      (( idx_pat == 0 )) && match_start=${#output}
      (( idx_pat += 1 ))

      if (( idx_pat == pat_len )); then
        idx_pat=0
        (( found += 1 ))
        if (( opt_find_only == 0 )); then
          if (( opt_trim_lines == 0 )); then
            local _d1; make_debug_str "${output:0:match_start}" _d1
            #local _d2; make_debug_str "${opt_replacement_text}" _d2
            output="${output:0:match_start}${opt_replacement_text}"
            [[ "${opt_replacement_text}" ]] && output+="${newline}"
          else
            #_d=; make_debug_str "${output:(match_start-1):1}" _d
            #local _d2; make_debug_str "${opt_replacement_text}" _d2
            ((match_start>0)) && _d2="hello"
            while ((match_start>0)) && [[ "${output:(match_start-1):1}" == [[:space:]] ]]; do
              match_start=$((match_start-1))
            done
            output="${output:0:match_start}${newline}${opt_replacement_text}"
            #local _d3; make_debug_str "${output}" _d3
            trim_forward_newlines=1
          fi
        elif (( opt_break_on_first == 1 )); then
          break
        fi
        continue
      fi
    else
      idx_pat=0
    fi

    (( opt_find_only == 0 )) && output+="$line${newline}"
  done

  if (( opt_find_only == 0 )); then
    # local _d=; make_debug_str "${output}" _d
    printf '%s' "${output}"
  elif (( found > 0)); then
    printf '%s' "$found"
  fi
  return 0
}

