#!/usr/bin/env bash

set -o nounset
 
declare -i PATCH_LENGTH=0
declare -a PATCH_LINES=()
declare -a FILE_LINES=()

declare __this_path;__this_path="$(dirname "${BASH_SOURCE[0]}")"
source "$__this_path/libs/version-lib"

# reads the patch file into the PATCH_LINES array.
# $1: the filename of the file to read
# PATCH_LENGTH is set to the number size of the array
_read_patch_lines() {
    local filename="${1}"
    [[ -f  "$filename" ]] || { echo "file-patcher: patcher-file not found: ${filename}"; return 1; } 
    mapfile -t PATCH_LINES < "$filename"
    PATCH_LENGTH=${#PATCH_LINES[@]}
}

# Writes the FILE_LINES array to file
# $1: the file name to write the FILE_LINES array too
_write_file_lines() {
    local filename="${1}"
    printf "%s\n" "${FILE_LINES[@]}" > "${filename}"
}

# shellcheck disable=SC2329
# inserts a new line in the FILE_LINES array
# $1: the index in the FILE_LINES array to insert the new line at
# $2: the string to insert
_insert_line() {
    local -i insert_at_index=${1}
    local line_to_insert="${2}"
 
    FILE_LINES=("${FILE_LINES[@]:0:$insert_at_index}" "${line_to_insert}" "${FILE_LINES[@]:$insert_at_index}")
}

# inserts a slice of PATCH_LINES (from start index ($2) to end index ($3)) into the FILE_LINES at index ($1)
# $1 insert index
# $2 patch start index
# $3 patch end index
# requires _read_file_lines & _read_patch_lines methods have been called
_insert_patch() {

    insert_at_index=${1}
    patch_start_index=${2}
    patch_len=$(($3-$2+1))

    FILE_LINES=("${FILE_LINES[@]:0:$insert_at_index}" "${PATCH_LINES[@]:patch_start_index:patch_len}" "${FILE_LINES[@]:$insert_at_index}")
}

# removes a range of lines from FILE_LINES using a start index and an end index
# $1: the start index
# $2: the end index
# requires _read_file_lines & _read_patch_lines methods have been called
# shellcheck disable=SC2329
_remove_range() {
    local -i remove_start_index=${1}
    local -i remove_end_index=${2}
    local -i remove_start_index=$((remove_start_index))
    local -i remove_end_index=$((remove_end_index+1))

    FILE_LINES=("${FILE_LINES[@]:0:$remove_start_index}" "${FILE_LINES[@]:remove_end_index}")
}

# finds the end of a patch segment usualy definded by '===='
# Arguments
# $1 : [in] the start position of the patch segment
# $2 : [in,out] patch_end
_getCommandBounds() {

    local patchcurpos=${1}
    local -n __patch_start=${2}
    local -n __patch_end=${3}
    local -i p=0

    if [[ ${PATCH_LINES[$patchcurpos]:0:1} == "@" ]]; then  
        __patch_start=$((patchcurpos+2))
    else
        __patch_start=$patchcurpos
    fi

    for (( p=__patch_start; p<PATCH_LENGTH; p++ )); do
 
        if [[ "${PATCH_LINES[$p]}" == "====" ]]; then
            __patch_end=$((p-1))
            break
        fi
    done
}
 
# finds the text in the FILE_LINES array using the text segment from the PATCH_LINES array
# Arguments:
# $1 : [in] direction (1=forwards,-1=backwards)
# $2 : [in] patch_start
# $3 : [in] patch_end
# $4 : [in,out] file_start
# $5 : [in,out] file_end
_find() {
    local  -i direction=${1}
    local  -i patch_start=${2}
    local  -i patch_end=${3}
    local -n __file_start=${4}
    local -n __file_end=${5}
	local -i comment_count=0 f=0 p=0
    local -i step=1
    local -i file_exit_index=${#FILE_LINES[@]}
    local -i patch_exit_index=$((patch_end+1))
    local -i patch_start_index=$patch_start
    local -i patch_done_index=$patch_end
    __file_start=-1; __file_end=-1; 
 
    if ((direction==-1)); then
        f=$((file_exit_index-1))
        patch_done_index=$patch_start
        step=-1; file_exit_index=-1; patch_exit_index=-1
        patch_start_index=$patch_end
    fi
    
    while ((f!=file_exit_index)); do

		p=$patch_start_index
		# trim white space when ,matching opening/closing comments \* */
		if [[ "${FILE_LINES[$f]}" =~ ^[[:space:]]*/\* ]]; then
            comment_count=$((comment_count+step))
        elif [[ "${FILE_LINES[$f]}" =~ ^[[:space:]]*\*/ ]]; then
            comment_count=$((comment_count-step))
		fi
        ((comment_count)) && { f=$((f+step)); continue; } # don't search in block comments

        while ((p!=patch_exit_index)); do

			if [[ "${FILE_LINES[$f]}" = "${PATCH_LINES[$p]}" ]] ; then
 
				if ((p==patch_start_index)); then
					__file_start=$f
				fi
				
                if ((p==patch_done_index)); then
                    if ((direction==-1)); then
                        __file_end=$__file_start
                        __file_start=$f
                    else
                        __file_end=$f
                    fi
                    break 2
                fi
                f=$((f+step))
			else
				__file_start=-1
				break
			fi
            p=$((p+step))
		done

        f=$((f+step))
	done

    # echo "__file_start:$__file_start,__file_end:$__file_end,patch_start:$patch_start,patch_end:$patch_end"
}
    

_openfile_command() {
    local -n __filename=$1
    local -n __index=$2
    local -n __fileopen=$3
 
    if ((__fileopen)); then
        _write_file_lines "$__filename"
        FILE_LINES=()
        __fileopen=0
    fi

    __index=$((__index+2))
    __filename="${PATCH_LINES[$__index]}"

    if [[ ! -f "$__filename" ]]; then
        echo "WARNING: File not found: $__filename" >&2
        __filename=""
        __index=$((__index+2))
        return
    fi
 
    # Read file into array FILE_LINES
    mapfile -t FILE_LINES < "$__filename"
    __fileopen=1
    __index=$((__index+2))
}

# shellcheck disable=SC2329
# reads the commands in a <name>.patch file and applys the result to the supplied file
# $1: the file containing the patch commands to apply.  
file_patcher_apply_patch() { 
  
    local patchfile="$1"
    local -i file_start=0 file_end=0
    local -i patch_start=0 patch_end=0
    local -i p=0 fileopen=0
    local -i direction=1

    _read_patch_lines "$patchfile" || return 1

    local venus_version="" patch_line="" command="" version_condition=""

    version_lib_get_venus_verion_byref venus_version

    while ((p < PATCH_LENGTH)); do
       
        #echo "index: $p, ${#PATCH_LINES[@]}, value: ${PATCH_LINES[$p]}"
        patch_line="${PATCH_LINES[$p]}"
        
        # Extract command (first word) and version condition
        command="${patch_line%% *}"
        version_condition=""
        
        # Check if there's a version condition
        if [[ "$patch_line" != "$command" ]]; then
            version_condition="${patch_line#* }"
            if ! version_lib_check "$version_condition" "$venus_version"; then
                _getCommandBounds $p patch_start patch_end
                p=$((patch_end+2)) # +2 to jmp direct to next cmd
                continue
            fi
        fi
        
        if [[ "$command" == "@openfile" ]]; then
            _openfile_command filename p fileopen
            continue
        fi
 
        ((!fileopen)) && { ((p+=1)); continue; }
 
        case "$command" in
        @find | @findbackwards)
            #echo "${PATCH_LINES[$p]}"
            direction=1; [[ $command == "@findbackwards" ]] && direction=-1
            _getCommandBounds $p patch_start patch_end
            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            _find $direction $patch_start $patch_end file_start file_end
            p=$((patch_end+1))
            ;;
        @insertbefore | @insertafter)
            #echo "${PATCH_LINES[$p]}"
            [[ $file_start -eq -1 ]] && { p=$((p+1)); continue; }
            
            _getCommandBounds $p patch_start patch_end
            # ensure patch has not already been applied
            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            
            # shellcheck disable=SC2034
            local -i fstart=$file_start fend=-1
            _find $direction $patch_start $patch_end fstart fend
            
            [[ $fstart -ne -1 ]] && { p=$((patch_end+1)); ((p+=1)); continue; }
            
            local -i insert_at_file_pos=$((file_start))
            [[ "$command" == @insertafter ]] && insert_at_file_pos=$((file_end+1))
            
            _insert_patch $insert_at_file_pos $patch_start $patch_end
            p=$((patch_end+1))
            file_start=-1; file_end=-1
            ;;
        @remove)
            #echo "${PATCH_LINES[$p]}"
            _getCommandBounds $p patch_start patch_end
            _find $direction $patch_start $patch_end file_start file_end 
            p=$((patch_end+1))
            
            [[ $file_start -eq -1 ]] && { ((p+=1)); continue; }
            
            file_end=$((file_end+1))
            _insert_line $file_end "*/"
            _insert_line $file_start "\*"
            ;;
        esac
        
        ((p+=1))
    done

    if ((fileopen)); then
        _write_file_lines "$filename"
    fi
}
 
# shellcheck disable=SC2329
# reverts the changes that were applied using the apply_patch method
# $1: the file containing the patch commands to revert.  
file_patcher_revert_patch() {
    local patchfile="$1"
    local -i file_start=0 file_end=0
    local -i patch_start=0 patch_end=0
    local -i insert_at_file_pos 
    local -i p=0 fileopen=0
 
    _read_patch_lines "$patchfile" || return 1

    local venus_version="" patch_line="" command="" version_condition=""

    version_lib_get_venus_verion_byref venus_version

    while ((p < PATCH_LENGTH)); do
 
        #echo "index: $p, ${#PATCH_LINES[@]}, value: ${PATCH_LINES[$p]}"
        patch_line="${PATCH_LINES[$p]}"
        
        # Extract command (first word) and version condition
        command="${patch_line%% *}"
        version_condition=""
        
        # Check if there's a version condition
        if [[ "$patch_line" != "$command" ]]; then
            version_condition="${patch_line#* }"
            if ! version_lib_check "$version_condition" "$venus_version"; then
                _getCommandBounds $p patch_start patch_end
                p=$((patch_end+1))
                continue
            fi
        fi
        
        if [[ "$command" == "@openfile" ]]; then
            _openfile_command filename p fileopen
            ((p+=1))
            continue
        fi
        
        ((!fileopen)) && { ((p+=1)); continue; }

        case "$command" in
        @remove)  

            _getCommandBounds $p patch_start patch_end
            _find 1 $patch_start $patch_end file_start file_end
            if ((file_start!=-1)) && [[ "${FILE_LINES[$file_start]}" == "/*" ]] ; then
                _remove_range $file_end $((file_end))
                _remove_range $file_start $((file_start))
            fi

            file_start=-1; file_end=-1; patch_start=-1; patch_end=-1
            ;;
        @insertbefore | @insertafter)

            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            _getCommandBounds $p patch_start patch_end
            _find 1 $patch_start $patch_end file_start file_end
 
            if ((file_start!=-1)); then
                _remove_range $file_start $file_end
            fi
        
            file_start=-1; file_end=-1; patch_start=-1; patch_end=-1
            ;;
        esac
        ((p+=1)); 
    done

    if ((fileopen)); then
        _write_file_lines "$filename"
    fi
}

if [[ "${1:-}" = "apply" ]]; then
    file_patcher_apply_patch "$2" "${3:-}"
elif [[ "${1:-}" = "revert" ]]; then
    file_patcher_revert_patch "$2" "$3"
elif [[ -n "${1:-}" ]]; then
    echo "file-patcher: Usage: $0 apply|revert <patch_file> <optional file_to_patch>"
fi


# file_patcher_apply_patch "opkg-manager.patch"