#!/usr/bin/env bash

# mark ourselfs as alreaded sourced
__SOURCE_COMMON_SOURCED=1

SOURCE_COMMON_CALLER=

addsource() {

  if [[ ${DEV_INSTALL:-} == 1 ]]; then
    if [[ -z ${VE_ROOT_PATH:-} ]]; then
      export VE_ROOT_PATH="${OPKG_ROOT_DIR:-}"
    fi
    echo "★ ${VE_ROOT_PATH}/data/opkg-manager/${1}" # $'\n'"====================="
  fi

  local file="${1}"
  local guard_var="__${file//[^a-zA-Z0-9_]/_}_SOURCED"
  shift 1

  [[ -n "${!guard_var:-}" ]] && return 0;

	SOURCE_COMMON_CALLER="${BASH_SOURCE[1]}"

  # Mark this file as loaded only if source succeeds; failed loads can retry later.
	# printf sets the guard_var to 1 ;-)

	# shellcheck disable=SC1090
	source "${VE_ROOT_PATH:-}/data/opkg-manager/${file}" \
    && printf -v "$guard_var" '%s' 1

	# shellcheck disable=SC2034
	SOURCE_COMMON_CALLER=

}
