#!/bin/bash

set -o nounset

this_path="$(dirname "${BASH_SOURCE[0]}")"

echo building /feeds/venus-data-opkg-manager-blind-install.tgz
tar czf $this_path/../../../feeds/release/opkg-manager/venus-data-opkg-manager-blind-install.tgz -C $this_path/src/ rc

echo done