#!/usr/bin/env bash

# unreachable SC2329,SC2317
# shellcheck disable=SC2329,SC2317
# modified in subshell
# shellcheck disable=SC2031
# shellcheck disable=SC2086
# shellcheck disable=SC2119

set -o nounset

this_path="$(dirname "${BASH_SOURCE[0]}")"

. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../../../scripts/libs/core-lib"
. "$this_path/../src/data/apps/mount-shares/mount-lib"

this_dir_full="$(core_lib_realpath_nosymlinks "${this_path}")"
output_dir="${this_dir_full}/output"

# shellcheck disable=SC2034
LOG_INDENT_CHAR= # turn off indenting so string compares are simpler
# shellcheck disable=SC2034
LOGLEVEL=1 # $LOGLEVEL_ERROR

clear_output() {
  mkdir -p "$output_dir"
  rm -fr "${output_dir:?}/"*
  mkdir -p "$(dirname "$mountpoint_conf_file")"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  clear_output
fi

# staging helpers
stage_get_server_ip() { hostname -I | cut -d' ' -f1; }
stage_get_server_ip_path() { echo "$(hostname -I | cut -d' ' -f1)/downloads"; }
# shellcheck disable=SC1037
stage_get_password() { echo "spoons_play_on_saturn$%#\$343@2"; }
stage_get_user_name() { echo "$USER"; }
stage_get_mount_point_dir() { echo "$output_dir/mountpoints/mymountpoint"; }

stage_get_mount_args() {
  echo "-t cifs //$(stage_get_server_ip_path) -o user=$(stage_get_user_name),pass=$(stage_get_password) $(stage_get_mount_point_dir)"
}

test_mount_prompts_for_name() {

  # Arrange
  mount_lib_mount_server() { return 0; }
  __mount_lib___read() { echo "ERROR: __read should not be called" >&3; exit 1; }

  local -a mount_args=()
  read -r -a mount_args <<< "$(stage_get_mount_args)"
  local stdout

  # Act
  stdout=$(mount_lib_mount --targetpath "$(stage_get_mount_point_dir)" -- "${mount_args[@]}" 2>&1)

  # Assert
  assert_eq "" "$stdout"
}

test_mount_fails_when_mount_args_missing() {

  # Arrange
  local stdout

  # Act
  stdout=$(mount_lib_mount -tp "$(stage_get_mount_point_dir)" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "ERROR: mount args missing" "$stdout"
}

test_mount_fails_when_targetpath_missing() {

  # Arrange
  local stdout
  local -a mount_args=()
  read -r -a mount_args <<< "$(stage_get_mount_args)"

  # Act
  stdout=$(mount_lib_mount -- "${mount_args[@]}" 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "ERROR: target path is required: --targetpath|-tp" "$stdout"
}

test_mount_succeeds_settings_added_to_mountpoints_conf_file() {

  # Arrange
  mount_lib_mount_server() { return 0; }
  local args
  args="$(stage_get_mount_args)"
  local -a mount_args=()
  read -r -a mount_args <<< "${args}"
  local target
  target="$(stage_get_mount_point_dir)"
  local expected
  expected="${args}"

  assert_file_not_exist "$mountpoint_conf_file"

  # Act
  mount_lib_mount --targetpath "${target}" -- "${mount_args[@]}" 2>/dev/null

  # Assert
  assert_exitcode 0
  assert_file_exists "$mountpoint_conf_file"
  assert_eq "${expected}" "$(<$mountpoint_conf_file)"
}

test_mount_succeeds_settings_already_exist_not_added_twice() {

  # Arrange
  mount_lib_mount_server() { return 0; }
  local args
  args="$(stage_get_mount_args)"
  local -a mount_args=()
  read -r -a mount_args <<< "${args}"
  local target
  target="$(stage_get_mount_point_dir)"
  local expected
  expected="${args}"

  assert_file_not_exist "$mountpoint_conf_file"
  echo "$expected" > "$mountpoint_conf_file"

  # Act
  mount_lib_mount --targetpath "${target}" -- "${mount_args[@]}" 2>/dev/null

  # Assert
  assert_exitcode 0

  local count_of=
  count_of=$(grep -o -- "$expected" "${mountpoint_conf_file}" | wc -l)
  assert_eq 1 "${count_of}"
  assert_eq "${expected}" "$(<$mountpoint_conf_file)"
}

test_mount_succeeds_mount_server_called_with_all_args() {

  # Arrange
  local test_log_file="${output_dir}/test.log"
  rm -f "$test_log_file"
  local expected
  expected="$(stage_get_mount_args)"
  local -a mount_args=()
  read -r -a mount_args <<< "${expected}"

  mount_lib_mount_server() {
    echo "$*" >> "$test_log_file"
  }

  # Act
  mount_lib_mount --targetpath "$(stage_get_mount_point_dir)" -- "${mount_args[@]}" 2>/dev/null

  # Assert
  assert_exitcode 0
  assert_eq "--targetpath $(stage_get_mount_point_dir) ${expected}" "$(<$test_log_file)"
}

test_mount_server_succeeds_creates_mount_target_folder() {

  # Arrange
  mount() { return 0; }
  local stdout
  local mount_point_path
  mount_point_path="$(stage_get_mount_point_dir)"

  assert_dir_not_exist "$mount_point_path"

  # Act
  exec 3>&1
  stdout="$(mount_lib_mount_server --targetpath "$mount_point_path" -t cifs "//$(stage_get_server_ip_path)" "$mount_point_path" -o "user=$(stage_get_user_name),pass=$(stage_get_password)" 2>&1)"

  # Assert
  assert_exitcode 0
  assert_dir_exists "$mount_point_path"
  assert_eq "" "$stdout"
}

test_mount_server_mount_fails_returns_exitcode_from_mount() {

  # Arrange
  local expected_exit_code=127
  mount() { return $expected_exit_code; }
  local stdout

  # Act
  stdout="$(mount_lib_mount_server --targetpath "$(stage_get_mount_point_dir)" -t cifs "//$(stage_get_server_ip_path)" "$(stage_get_mount_point_dir)" -o "user=$(stage_get_user_name),pass=$(stage_get_password)" 2>&1)"

  # Assert
  assert_exitcode $expected_exit_code
  assert_eq "ERROR: mount returned exit code $expected_exit_code" "$stdout"
}

test_mount_all_succeeds_calls_mount_correctly() {

  # Arrange
  local test_log_file="${output_dir}/test.log"
  rm -f "$test_log_file"

  mount_lib_mount_server() {
    echo "$*" >> "$test_log_file"
  }

  local args_1 args_2
  args_1="$(stage_get_mount_args)"
  args_2="-t cifs //$(stage_get_server_ip_path) -o user=$(stage_get_user_name),pass=$(stage_get_password) ${output_dir}/mountpoints/second"

  {
    echo "${args_1}"
    echo "invalid_line_without_pipe"
    echo "${output_dir}/mountpoints/empty"
    echo "${args_2}"
  } > "$mountpoint_conf_file"

  # Act
  mount_lib_mount_all 2>/dev/null
  sleep 1

  # Assert
  assert_exitcode 0
  assert_file_exists "$test_log_file"

  local mount_count
  mount_count="$(wc -l <"$test_log_file")"
  assert_eq "2" "$mount_count"
  assert_file_contains "$test_log_file" "$args_1"
  assert_file_contains "$test_log_file" "$args_2"
}

test_mount_lib_wait_on_mount_point_succeeds_when_mount_exists() {

  # Arrange
  mountpoint() {
    return 0
  }

  local stdout
  local mount_point="/mnt/some_mount_point"

  # Act
  stdout=$(mount_lib_wait_on_mount_point "$mount_point" 2>&1)

  # Assert
  assert_exitcode 0
  assert_eq "mountpount available: ${mount_point}" "$stdout"
}

test_mount_lib_wait_on_mount_point_fails_when_mount_times_out() {

  # Arrange
  mountpoint() {
    return 1
  }

  local stdout
  local mount_point="/mnt/some_mount_point"

  # Act
  stdout=$(mount_lib_wait_on_mount_point "$mount_point" 2 2>&1)

  # Assert
  assert_exitcode 1
  assert_eq "mountpount not available: ${mount_point}" "$stdout"
}

test_mount_lib_wait_on_mount_point_quiet_returns_empty_stdout() {

  # Arrange
  local retval=0
  mountpoint() {
    return $retval
  }

  local stdout_success stdout_fail
  local mount_point="/mnt/some_mount_point"

  # Act
  stdout_success=$(mount_lib_wait_on_mount_point "$mount_point" --quiet 2>&1)
  retval=1
  stdout_fail=$(mount_lib_wait_on_mount_point "$mount_point" 1 --quiet 2>&1)

  # Assert
  assert_eq "" "$stdout_success"
  assert_eq "" "$stdout_fail"
}

test_mount_lib_remove_mount_succeeds_removes_entry_by_target() {

  # Arrange
  local -i index=1
  local -a mounts=()
  local -a targets=()
  local mount line

  rm -f "${mountpoint_conf_file}"

  while ((index < 4)); do
    target="${output_dir}/mountpoints/mount_${index}"
    mount="-t cifs //$(stage_get_server_ip_path) ${target} -o user=$(stage_get_user_name),pass=$(stage_get_password)"
    mounts+=("${mount}")
    targets+=("${target}")
    echo "$mount" >> "${mountpoint_conf_file}"
    ((index += 1))
  done

  local count_of=
  count_of=$(wc -l <<< "$(<"$mountpoint_conf_file")")
  assert_eq 3 "${count_of}"

  # Act
  mount_lib_remove_mount "${targets[1]}"

  # Assert
  index=0
  while read -r line; do
    ((index == 1)) && { ((index += 1)); continue; }
    assert_eq "${mounts[$index]}" "${line}"
    ((index += 1))
  done < "$mountpoint_conf_file"
}

pre_test_runner() {
  clear_output
}

post_test_runner() {
  true
}

if [[ "${0:-}" == "${BASH_SOURCE[0]}" ]]; then
  test_runner_all --summary ""
  exit
fi
