#!/bin/bash


this_path="$(dirname "${BASH_SOURCE[0]}")"

. "$this_path/../scripts/libs/test-lib"

test_file="$1"
test_function_filter="${2:-^test_.*}"

if [[ -z "$test_file" ]]; then
	echo "Usage: $0 <test-file> [regex-filter]" >&2
	exit 1
fi

test_runner_on_source_file --summary "$test_file" "$test_function_filter"
