#!/bin/bash
# German (de)
# shellcheck disable=SC2034

LANG_PACKAGE_INSTALLING_ARG1="Installiere %s"
LANG_PACKAGE_REMOVING_ARG1="Entferne %s"
LANG_PACKAGE_UPGRADING_ARG1="Aktualisiere %s"
LANG_PACKAGE_INSTALL="Installieren"
LANG_PACKAGE_REMOVE="Entfernen"
LANG_PACKAGE_UPGRADE="Aktualisieren"
LANG_PACKAGE_SUCCEEDED=" erfolgreich"
LANG_PACKAGE_ARG1_FAILED_ARG2="%s fehlgeschlagen (Status %s)"
LANG_PACKAGE_UPDATING_PACKAGES="Pakete werden aktualisiert"

LANG_DEVICE_REMOVING_SERIAL_DEVICE_SERVICE="Entferne den seriellen Gerätedienst"
LANG_DEVICE_REMOVING_DEVICE_SETTINGS_ARG1="Entferne Geräteeinstellungen %s"