#!/bin/sh

VERSION=1.7
VESPERA_VERBOSITY=1

case "$1" in -V[0-4]) VESPERA_VERBOSITY="${1#-V}" ;; esac

printf "Install Vespera? [n/Y] "
read -r answer; [ "$answer" = n ] || [ "$answer" = N ] && { echo "Cancelled."; exit 0; }

VESPERA_DATA_DIR="/data/var/vespera"
OPKG_CONF="${VESPERA_DATA_DIR}/bootstrap-opkg.conf"

echo "Installing Vespera"
echo "Bootstrap version: $VERSION"

mkdir -p "${VESPERA_DATA_DIR}/lists" "${VESPERA_DATA_DIR}/info"

cat > "${OPKG_CONF}" <<EOF
dest root /
option lists_dir ${VESPERA_DATA_DIR}/lists
option info_dir ${VESPERA_DATA_DIR}/info
option status_file ${VESPERA_DATA_DIR}/status
option cache_dir /tmp
EOF

__cleanup() { trap - EXIT; rm -f "/var/lock/vespera"; rm -rf "$OPKG_CONF" "$VESPERA_WORKING_DIR"; } # "$VESPERA_WORKING_DIR"

mkdir -p /var/lock/
VESPERA_WORKING_DIR="$(mktemp -d /tmp/vespera-XXXXXX)" || return 1
ln -sfn "$VESPERA_WORKING_DIR" "/var/lock/vespera"
[ "$VESPERA_VERBOSITY" != 1 ] && echo "$VESPERA_VERBOSITY" > "$VESPERA_WORKING_DIR/verbosity"

trap '__cleanup' EXIT

fsresize="/opt/victronenergy/swupdate-scripts/resize2fs.sh"
[ -f "$fsresize" ] && {
    echo "Resizing file system"
    [ "$VESPERA_VERBOSITY" -gt 1 ] && output="/dev/stdout" || output="/dev/null"
    ("$fsresize" && mount -o remount,ro /) >"$output" 2>&1
}


opkg -f "${OPKG_CONF}" "$@" install "http://192.168.10.32:8808/develop/vespera-latest.ipk" || exit
retval=$?

# shellcheck disable=SC1091
( . "/data/apps/available/vespera/libs/vespera-lib"; vespera_lib_bootstrap; )

__cleanup

echo "Vespera installed."
exit $retval
