#!/bin/sh

set -e

echo "version 1.2"

VESPERA_DIR="/data/var/vespera"
OPKG_CONF="${VESPERA_DIR}/opkg.conf"

mkdir -p \
    "${VESPERA_DIR}/lists" \
    "${VESPERA_DIR}/info" \
    "${VESPERA_DIR}/cache"

cat > "${OPKG_CONF}" <<EOF
dest root /

option lists_dir ${VESPERA_DIR}/lists
option info_dir ${VESPERA_DIR}/info
option status_file ${VESPERA_DIR}/status
option cache_dir ${VESPERA_DIR}/cache

src/gz vespera http://192.168.10.32:8808/develop
EOF

echo "Installing Vespera..."

opkg -f "${OPKG_CONF}" install \
    "http://192.168.10.32:8808/develop/vespera-latest.ipk"

rm -f "$OPKG_CONF"

vespera update

echo "Vespera installed."