#!/usr/bin/env bash

__vespera_path="$(dirname "${BASH_SOURCE[0]}")"
__vespera_path="$(cd "${__vespera_path}/.." && pwd)"

# shellcheck source="../conf-default/vespera.conf"
source "$__vespera_path/conf/vespera.conf"
VESPERA_DATA_DIR="${VESPERA_ROOT:-}${VESPERA_DATA_DIR}"
# shellcheck source="../libs/opkg-lib"
source "$__vespera_path/libs/opkg-lib"

declare _venus_services_to_restart=()
declare _refresh_devices=

for app in $(opkg_lib_list_enabled_packages "all"); do
	[[ "$#" -eq 0 ]] || [[ " $* " == *" $app "* ]] || continue
	app="${app##*/}"

	"${__vespera_path}/scripts/remove-services" "${app}" ___refresh_devices
	"${VESPERA_DATA_DIR}/info/vespera.overlay-lib" overlay-unregister "${app}";

	declare dbus_name; dbus_name=$(cat "$VESPERA_DATA_DIR/info/${app}.${VESPERA_DBUS_NAME}")
	[[ -n $dbus_name ]] &&
		dbus -y com.victronenergy.settings "/Settings/Vespera/Packages/$dbus_name/Enabled" SetValue "0" 1>/dev/null 2>&1

	rm -f "${VESPERA_ROOT:-}/data/apps/enabled/$app"
	_venus_services_to_restart+=("$VESPERA_DATA_DIR/info/$app.installer-services")
done

declare -p _refresh_devices _venus_services_to_restart