#!/usr/bin/env bash

__vespera_path="$(dirname "${BASH_SOURCE[0]}")"
__vespera_path="$(cd "${__vespera_path}/.." && pwd)"

# shellcheck source="../conf-default/vespera.conf"
source "$__vespera_path/conf/vespera.conf"
VESPERA_DATA_DIR="${VESPERA_ROOT:-}${VESPERA_DATA_DIR}"
# shellcheck source="../libs/opkg-lib"
source "$__vespera_path/libs/opkg-lib"

__enable_app() {
	local app="${1}"
	local -n __refresh_devices="${2}"
	local enabled_apps_dir="${VESPERA_ROOT:-}/data/apps/enabled"
	local available_app_path="${VESPERA_ROOT:-}/data/apps/available/${app}"
	local retVal

	[[ ! -d "$available_app_path" ]] && return

	local dbus_name; dbus_name=$(cat "$VESPERA_DATA_DIR/info/${app}.${VESPERA_DBUS_NAME}" 2>/dev/null)
	local overlay_targets_conf="$VESPERA_DATA_DIR/info/${app}.installer-overlays"

	[[ -f "$overlay_targets_conf" ]] &&
		"${VESPERA_DATA_DIR}/info/vespera.overlay-lib" overlay-register "${app}" <"$overlay_targets_conf"

	retVal=$("$__vespera_path/scripts/start-app-services" "${app}" "${dbus_name}")
	[[ $retVal == 2 ]] && __refresh_devices=true

	[[ -n $dbus_name ]] &&
		dbus -y com.victronenergy.settings "/Settings/Vespera/Packages/$dbus_name/Enabled" SetValue "1" 1>/dev/null 2>&1

	[[ -d "$available_app_path" && ! -e "$enabled_apps_dir/$app" ]] && {
		mkdir -p "$enabled_apps_dir"
		[[ -f "${available_app_path}/gui-v2/${app}.json.install" ]] &&
			mv "${available_app_path}/gui-v2/${app}.json.install" "${available_app_path}/gui-v2/${app}.json"
		ln -sf "$available_app_path" "$enabled_apps_dir/$app"
	}

}

declare _venus_services_to_restart=()
declare _refresh_devices=

for app in $(opkg_lib_list_packages "all"); do
	[[ "$#" -eq 0 ]] || [[ " $* " == *" $app "* ]] || continue
	__enable_app "$app" _refresh_devices
	_venus_services_to_restart+=("$VESPERA_DATA_DIR/info/$app.installer-services")
done

# outputs the attributes of each variable, use eval to restore variable
declare -p _refresh_devices _venus_services_to_restart
