#!/usr/bin/env bash

# Loops though all the installed applications under /data/var/vespera/info
# looking for startup files in the format [app name].rcS|rc-[0-9]-local
# example dbus-inetbox.rcS-8-local | themer.rc-50-local
# Files are sorted by the numeric value. The numeric value indicates the order the script is executed.
# The app name is extracted from the file name and is checked if the app is enabled before executing

__vespera_path="$(dirname "${BASH_SOURCE[0]}")"
__vespera_path="$(cd "${__vespera_path}/.." && pwd)"

# shellcheck source="../conf-default/vespera.conf"
source "$__vespera_path/conf/vespera.conf"
VESPERA_DATA_DIR="${VESPERA_ROOT:-}${VESPERA_DATA_DIR}"

declare startup_type="${1%.*}" # strip the extension; rcS.local becomes rcS
declare script_path=
declare filename=

declare enabled_apps_dir="${VESPERA_ROOT:-}/data/apps/enabled"

while read -r script_path; do
	[[ -z "$script_path" ]] && continue
	filename="${script_path##*/}"
	filename="${filename%.*}"
	[[ ! -e "${enabled_apps_dir}/$filename" ]] && { echo "App not enabled skipping: $script_path"; continue; }

	echo "$(date +%Y-%m-%d\ %H:%M:%S) executing... $script_path"
	# shellcheck disable=SC1090
	(. "$script_path" )

done < <( find "$VESPERA_DATA_DIR/info" -maxdepth 1 -type f -name '*.'"$startup_type"'-[0-9]*-local' | \
  				awk -F'-' '{print $(NF-1), $0}' |  sort -n | cut -d' ' -f2-
				)
