#!/usr/bin/env bash

declare root_prefix="${VESPERA_ROOT:-}"
declare serial_starter_path="${root_prefix}/service/serial-starter"
declare serial_starter_dev="${root_prefix}/dev/serial-starter"
declare serial_starter_lock_dir="${root_prefix}/var/lock/serial-starter"
declare serial_starter_up=false

svstat "${serial_starter_path}" | grep -q "^${serial_starter_path}: up " && serial_starter_up=true

rm -f "${serial_starter_dev}/"*
svc -d "${serial_starter_path}"

# clear stale locks, (causes lots of issues)
rm -f "${serial_starter_lock_dir}/tty*"

udevadm control --reload-rules >/dev/null;
udevadm trigger --action=add --subsystem-match=tty --property-match=ID_BUS=usb >/dev/null
udevadm settle >/dev/null

[[ $serial_starter_up == true ]]
	svc -u "${serial_starter_path}"
