#!/usr/bin/env bash

declare -n services_array="$1"
declare verbosity="${2:-1}"
declare service

for file in "${services_array[@]}"; do
	[[ -f "$file" ]] || continue
	cat "$file"
done | sort -u | while IFS= read -r service || [ -n "$service" ]; do
	service="${service%%#*}"
	service="${service#"${service%%[![:space:]]*}"}"
	service="${service%"${service##*[![:space:]]}"}"
	[[ -z "$service" ]] && continue
	[[ $verbosity -gt 1 ]] && echo "restarting $service"
	[[ ! -d "$service" ]] && continue
	svc -t "$service"
done