#!/usr/bin/env bash
# shellcheck disable=SC2034

PACKAGE_DBUS_NAME="NeShunt"

declare -A PACKAGE_DEVICE=(
	["dbus-ne-shunt"]="Ne Shunt"
)

PACKAGE_CUSTOM_OVERVIEW_PAGES=(NeShuntOverview)

PACKAGE_DBUS_SETTINGS=
PACKAGE_DBUS_SETTINGS_DEPRECATED=

# shellcheck source=/data/dev/addons/vespera/src/data/apps/available/vespera/libs/source-lib
source "${VESPERA_ROOT:-}/data/apps/vespera/libs/source-lib"
addsource libs/installer-lib "$@"
