#!/bin/bash

if [[ -n "$D" ]]; then
  return;
fi

declare package_name="network-gps" #get file name without path
declare service_name="$package_name"

# copy service, svscan will detect the new files & avoid a reboot
cp -R "/opt/victronenergy/service/${service_name}/" /service/

# shellcheck source=/data/dev/addons/vespera/src/data/apps/vespera/libs/opkg-lib
source "/data/apps/vespera/libs/opkg-lib"
opkg_lib_register_package "${package_name}"

echo "${package_name} installed"
