#!/bin/sh
set -e
if [ -n "$D" ]; then
  return 0
fi

package_name="$(basename "${0%.*}")" #get file name without path
service_name="$package_name"

# Stop services to avoid a reboot
svc -d "/service/${service_name}"
sleep 1
rm -R "/service/${service_name}"

## Remove conf file
# rm -r "/data/conf/${package_name}.conf"

# Clear logs
if [ -f "/var/log/${service_name}" ]; then
  rm -R "/var/log/${service_name}"
fi

# shellcheck source=../../../../addons/vespera/src/data/apps/vespera/libs/opkg-lib
. "/data/apps/vespera/libs/opkg-lib"
opkg_lib_unregister_package "${package_name}"

echo "${package_name}" removed
