#!/bin/env bash

declare __this_path; __this_path="$(dirname "${BASH_SOURCE[0]}")"

repo_root="/data/dev/addons/vespera"
echo "hello"
needs_rebuild() {
	local _src_dir=${1}
	local _output_bin=${2}
	[[ ! -f "$_output_bin" ]] && return 0
	find "$_src_dir" -type f -newer "$_output_bin" -print -quit | grep -q .
}

src_dir="$__this_path/gui-v2/Vespera"
output_bin="$repo_root/src/data/apps/available/vespera/gui-v2/vespera.json"

if needs_rebuild "$src_dir" "$output_bin"; then

	echo "  building plugin..." >&3
	cd "$src_dir" || exit
	./build-plugin 2>&3 # 192.168.10.24
fi

src_dir="$repo_root/src-external/opkg-json-indexer"
output_dir="$repo_root/src/data/apps/available/vespera/bin"
output_bin="$output_dir/opkg-json-indexer"

if needs_rebuild "$src_dir" "$output_bin"; then

	echo "  building opkg-json-indexer..." >&3
	$src_dir/build-indexer
fi
