#!/bin/bash
# shellcheck disable=SC2155

PKG_WORKING_DIR="$(readlink ${VESPERA_ROOT:-}/var/lock/vespera)"
PKG_SOURCE="${0}"
PKG_ACTION="${1}"
PKG_NAME="${PKG_SOURCE##*/}"; PKG_NAME="${PKG_NAME%%.*}"
PKG_OVERLAY_LIB="${VESPERA_ROOT:-}/data/var/vespera/info/vespera.overlay-lib"

export VESPERA_VERBOSITY=$(cat "${PKG_WORKING_DIR}/verbosity" 2>/dev/null || echo 1)

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo "postrm"
	echo "VESPERA_VERBOSITY=$VESPERA_VERBOSITY"
	echo "PKG_SOURCE=${PKG_SOURCE}"
	echo "PKG_NAME=$PKG_NAME"
	echo "PKG_ACTION=$PKG_ACTION"
	echo "PKG_OVERLAY_LIB=$PKG_OVERLAY_LIB"
fi

if [[ $PKG_ACTION != "upgrade" ]]; then
	"${PKG_OVERLAY_LIB}" overlay-unregister "${PKG_NAME}"
fi

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo
fi
