#!/bin/bash
# shellcheck disable=SC2155

PKG_WORKING_DIR="$(readlink ${VESPERA_ROOT:-}/var/lock/vespera)"
PKG_SOURCE="${0}"
PKG_ACTION="${1}"
PKG_SCRIPT_DIR="${PKG_SOURCE%/*}"
PKG_NAME="$(sed -n 's/^Package:[[:space:]]*//p' "${PKG_SCRIPT_DIR}/control" | head -n 1)"
PKG_OVERLAY_CONF_FILE="${PKG_SCRIPT_DIR}/installer-overlays"
PKG_OVERLAY_LIB="${PKG_SCRIPT_DIR}/overlay-lib"

VESPERA_VERBOSITY=$(cat "${PKG_WORKING_DIR}/verbosity" 2>/dev/null || echo 1)

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo "preinst"
	echo "VESPERA_VERBOSITY=$VESPERA_VERBOSITY"
	echo "PKG_SOURCE=${PKG_SOURCE}"
	echo "PKG_NAME=$PKG_NAME"
	echo "PKG_ACTION=$PKG_ACTION"
	echo "PKG_OVERLAY_LIB=$PKG_OVERLAY_LIB"
	echo "PKG_SCRIPT_DIR=$PKG_SCRIPT_DIR"
	echo "PKG_OVERLAY_CONF_FILE=$PKG_OVERLAY_CONF_FILE"
fi

"${PKG_OVERLAY_LIB}" overlay-register "${PKG_NAME}" < "${PKG_OVERLAY_CONF_FILE}"

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo
fi