#!/bin/bash
# shellcheck disable=SC2155

PKG_WORKING_DIR="$(readlink ${VESPERA_ROOT:-}/var/lock/vespera)"
PKG_SOURCE="${0}"
PKG_ACTION="${1}"
PKG_NAME="${PKG_SOURCE##*/}"; PKG_NAME="${PKG_NAME%%.*}"
PKG_SCRIPT_DIR="${PKG_SOURCE%/*}"
PKG_INSTALLER_FILE="${PKG_SCRIPT_DIR}/${PKG_NAME}.installer"
PKG_REMOVE_SCRIPT="${VESPERA_ROOT:-}/data/apps/available/vespera/scripts/remove"
PKG_OVERLAY_CONF_FILE="${PKG_SCRIPT_DIR}/vespera.installer-overlays"
PKG_OVERLAY_LIB="${PKG_SCRIPT_DIR}/vespera.overlay-lib"

VESPERA_VERBOSITY=$(cat "${PKG_WORKING_DIR}/verbosity" 2>/dev/null || echo 1)

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo "prerm"
	echo "VESPERA_VERBOSITY=$VESPERA_VERBOSITY"
	echo "PKG_SOURCE=${PKG_SOURCE}"
	echo "PKG_NAME=$PKG_NAME"
	echo "PKG_ACTION=$PKG_ACTION"
	echo "PKG_SCRIPT_DIR=$PKG_SCRIPT_DIR"
	echo "PKG_INSTALLER_FILE=$PKG_INSTALLER_FILE"
	echo "PKG_REMOVE_SCRIPT=$PKG_REMOVE_SCRIPT"
	echo "PKG_OVERLAY_CONF_FILE=$PKG_OVERLAY_CONF_FILE"
	echo "PKG_OVERLAY_LIB=$PKG_OVERLAY_LIB"
fi

"$PKG_REMOVE_SCRIPT" "$PKG_ACTION" "$PKG_INSTALLER_FILE" "$PKG_WORKING_DIR" "$VESPERA_VERBOSITY"

"${PKG_OVERLAY_LIB}" overlay-register "${PKG_NAME}" < "${PKG_OVERLAY_CONF_FILE}"

if ((VESPERA_VERBOSITY>1)); then
	echo "*****************************************************"
	echo
fi
