#!/usr/bin/env bash

set -o nounset

declare config_dir="/data/conf/vespera"
declare base_feed_url="https://thespinmaster.github.io/venus-os-addons/feeds"
declare feeds_file_release="${config_dir}/feeds-release.conf"
declare dev_mount_point="/data/mnt/dev"
declare opkg_feed_file="/etc/opkg/vespera.conf"
declare dev_link="/data/dev"

dev_setup_prompt_run_yes_no() {
	declare prompt_message=$1
	shift

	declare confirm=
	while read -r -p "${prompt_message}? (y/n): " confirm; do
		case "${confirm}" in
			y|Y|yes|YES)
				"$@"
				return $?;;
			n|N|no|NO)
				#echo "skipping command"
				return 1;;
			*)
				echo "invalid response"
				continue;;
		esac
	done
}

dev_setup_set_feed() {
	local feed_name="${1}"
	local feed_file="${config_dir}/feeds-${feed_name}.conf"
	if [[ ! -f "${feed_file}" ]]; then
		if [[ "${feed_name}" == "release" ]]; then
			dev_setup_opkg_release_feeds
		else
			dev_setup_opkg_named_feeds "${feed_name}"
		fi
	fi
	mkdir -p "${config_dir}"
	ln -sf "${feed_file}" "$opkg_feed_file"
	echo "using feed: ${feed_file}"
	cat "${feed_file}"| sed 's/^/    /' # sed adds some indenting
}

# Basic IPv4 format check
dev_setup_validate_local_ip_address() {
		local ip="$1"

		[[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

		IFS='.' read -r o1 o2 o3 o4 <<< "$ip"
		[ -n "$o4" ] || return 1

		for o in "$o1" "$o2" "$o3" "$o4"; do
				[[ "$o" =~ ^[0-9]+$ ]] && [ "$o" -le 255 ] || return 1
		done

		[ "$o1" -eq 10 ] && return 0
		[ "$o1" -eq 192 ] && [ "$o2" -eq 168 ] && return 0
		[ "$o1" -eq 172 ] && [ "$o2" -ge 16 ] && [ "$o2" -le 31 ] && return 0

		return 1
}

dev_setup_dns_resolver() {
	local nameserverline; nameserverline=$(head -n1 /etc/resolv.conf)
	if [[ ${nameserverline} == "nameserver 127.0.0.1" ]]; then

		while true; do
			read -r -p "Enter local dns nameserver ip [192.168.xx.xx]: " nameserverIP
			[[ -z "$nameserverIP" ]] && return 1
			dev_setup_validate_local_ip_address "$nameserverIP" || continue
			break;
		done
		nameserverline="nameserver $nameserverIP"
		sed -i "1c\nameserver $nameserverIP" /etc/resolv.conf
	fi
	echo "✅ name server set: ${nameserverline}"

}

dev_setup_opkg_named_feeds() {
	local feed_name="${1}"
	local feeds_server=

	read -r -p "Enter local feed server [empty to use github feed]: " feeds_server
	if [[ -z $feeds_server ]]; then
		feeds_server="$base_feed_url"
	else
		feeds_server="${feeds_server%/}"
		feeds_server_host="${feeds_server#http://}"
		feeds_server_host="${feeds_server_host#https://}"
		feeds_server_host="http://${feeds_server_host}"
	fi

	local feeds_file_name="$config_dir/feeds-${feed_name}.conf"

	cat > "$feeds_file_name" << EOF
src/gz vespera $feeds_server_host/develop/vespera
src/gz addons $feeds_server_host/develop/addons
EOF

	echo ✅ created $feed_name feeds: "$feeds_file_name"

	cat "$feeds_file_name" | sed 's/^/    /' # sed does some indenting

}

dev_setup_opkg_release_feeds() {

	cat > "$feeds_file_release" << EOF
	src/gz vespera $base_feed_url/release/vespera
	src/gz addons $base_feed_url/release/addons
EOF
 echo ✅ created release feeds: $feeds_file_release
}
dev_setup_create_dev_symlink() {

	if [ ! -L "$dev_link" ] || [ ! -e "$dev_link" ]; then
		local path=
		read -r -p "Enter path for $dev_link symlink [/mnt/dev/repos/venus-os]: " path
		[[ -z "$path" ]] && path="${dev_mount_point}/repos/venus-os"
		[[ ! -d "$path" ]] && { echo "ERROR:path does not exist" >&2; return 1; }
		ln -sfn "${path}" "$dev_link"
	fi

	echo "✅ dev share setup: $(readlink "$dev_link") -> $dev_link"
}

dev_setup_share() {

	declare share_source share_username share_password

	# source, username and password are prompted here and passed through to mount.
	read -r -p "Enter server ip/host address and share path [//192.168.1.10/dev]: " share_source
	read -r -p "Enter username for share: " share_username
	read -r -s -p "Enter password for share: " share_password
	echo
	[[ -z $share_source ]] && return

	# store mnt under /data and not /mnt as mnt may be readonly.
	# `unix` enables real symlink support on the CIFS dev share.
	# `unix` creates real symlinks unlike mfsymlinks.
	/data/apps/mount-shares/mount-lib mount --targetpath "$dev_mount_point" -- \
		-t cifs \
		-o "username=${share_username},password=${share_password},exec" \
		"${share_source}"

	ln -sf "$dev_mount_point/repos/venus-os" "$dev_link"

}

setup_vs_code_drive() {

	# CHECK FOR REMOVABLE DISKS
	if ! lsblk -nr -e 11 -o rm | awk '$1==1 {found=1} END{exit !found}'; then
		echo "no removable disks found; exiting..."
		return 1
	fi

	echo "=Removable Disks================================================="
	lsblk -e 11 -o rm,name,size,type,tran,model,rm,mountpoint | awk '$1 != RM' | cut -c4-
	echo "================================================================="

	# MENU
	PS3='Select the removable disk to use (or CTRL+C): '

	disks=()
	mounts=()

	while read -r name mount; do
		disks+=("$name")
		mounts+=("$mount")
	done < <(lsblk -nr -e 11 -o name,rm,type,mountpoint \
		| awk '$2==1 && $3=="part" {print $1, $4}')

	select disk in "${disks[@]}"; do
		if [[ -z "${disk:-}" ]]; then
			echo "$REPLY is not a valid number"
			continue
		fi

		mountpoint="${mounts[$((REPLY-1))]}"

		if [[ -z "$mountpoint" || ! -d "$mountpoint" ]]; then
			echo "Selected device is not mounted"
			return 1
		fi
		break
	done

	# TARGET SETUP
	local home_dir="$HOME"
	local target_link="$home_dir/.vscode-server"
	local dest="$mountpoint/.vscode-server"

	# VALIDATE dest CONFLICT
	if [[ -e "$dest" ]]; then
		echo "ERROR: destination already exists: $dest"
		return 1
	fi

	# HANDLE EXISTING HOME CONFIG
	if [[ -e "$target_link" && ! -L "$target_link" ]]; then
		echo "Existing ~/.vscode-server detected."

		printf "Move it to %s? [y/N]: " "$dest"
		read -r ans

		case "$ans" in
			y|Y|yes|YES)
				echo "Moving existing data..."
				mv "$target_link" "$dest"
				;;
			*)
				echo "Aborting."
				return 1
				;;
		esac

	elif [[ -L "$target_link" ]]; then
		echo "Existing symlink found. Removing it..."
		rm -f "$target_link"
	fi

	# ENSURE DESTINATION
	mkdir -p "$dest"

	# fix ownership (best effort)
	chown -R "$(id -u)":"$(id -g)" "$dest" 2>/dev/null || true

	# CREATE SYMLINK
	ln -s "$dest" "$target_link"

	echo "$target_link -> $dest"

}

dev_setup_package_installed() {
	local installed; installed=$(opkg list-installed "$1" | grep "^$1 ")

	if [[ "${2:-}" != "--quiet" && -n "$installed" ]]; then
		echo ✅ "$installed" already installed
		return 0
	else
		return 1
	fi
}

dev_setup_prompt_for_feed() {

	local current_feed=
	while read -r -p "Select feed [develop|release] :" current_feed; do
		[[ -z $current_feed ]] && current_feed="develop"
		case "${current_feed}" in
			"")
				continue;;
			*)
			break;;
		esac
	done

	dev_setup_set_feed "${current_feed}"
}

dev_setup_default_path() {
	# make data the default folder when logging in via ssh
	grep -qxF "cd /data" ~/.profile || echo "cd /data" >> ~/.profile
}

dev_setup_profile() {
	file=~/.profile

	prefix="export OPKG_ROOT_DIR="

	existing_export=$(grep -m1 "^$prefix" "$file")

	if [[ -n "$existing_export" ]]; then
		echo "✅ Found: $existing_export in ~/.profile"
	fi

	read -r -p "Enter the vespera develop path [/data/dev/addons/... or '-' to clear]: " dev_path

	# empty input → do nothing
	[[ -z "$dev_path" ]] && return

	# delete case
	if [[ "$dev_path" == "-" ]]; then
		sed -i "/^$prefix/d" "$file"
		echo "🗑️ Removed OPKG_ROOT_DIR from $file"
		return
	fi

	# normalize trailing backslash
	dev_path="${dev_path%\\}"

	if [[ ! -d "${dev_path}/vespera/src/" ]]; then
		echo "ERROR: dev path does not exist: ${dev_path}/vespera/src/"
		return
	fi

	new_export="${prefix}${dev_path}/vespera/src/"

	if [[ -n "$existing_export" ]]; then
		sed -i "s|^$prefix.*|$new_export|" "$file"
		echo "🔁 Updated: $new_export"
	else
		echo "$new_export" >> "$file"
		echo "✅ Added: $new_export"
	fi
}

dev_setup() {
	###############################################################################
	# DEV SETUP
	###############################################################################
	echo
	echo "configuring file system"

	/opt/victronenergy/swupdate-scripts/resize2fs.sh

	# make /data the default folder for connecting via sftp
	# find 'Subsystem       sftp    /usr/libexec/sftp-server'
	# and add '-d /data' to the end
	sed 's#Subsystem\s*sftp\s*/usr/libexec/sftp-server#Subsystem       sftp    /usr/libexec/sftp-server -d /data#' /etc/ssh/sshd_config 1>/dev/null

	dev_setup_dns_resolver

	local -i installed=

	[[ ! -f "/etc/opkg/vespera.conf" ]] &&
		rm -f "/etc/opkg/vespera.conf" # force removal if link target or file does not exist

	if ! opkg list-installed | grep -q "git -"; then
		dev_setup_prompt_run_yes_no "Install git" opkg install git
	else
		echo ✅ git already installed
	fi

	if ! opkg list-installed | grep -q "libatomic1 -"; then
		dev_setup_prompt_run_yes_no "Install libatomic1" opkg install libatomic1
	else
		echo ✅ libatomic1 already installed
	fi

	dev_setup_opkg_release_feeds

	if [[ -f "$feeds_file_develop" ]]; then
		echo ✅ dev opkg feeds file already exists: $feeds_file_develop
		cat "$feeds_file_develop" | sed 's/^/    /' # sed does some indenting
	fi

	dev_setup_prompt_run_yes_no "Setup dev opkg feeds" dev_setup_opkg_develop_feeds "develop"

	dev_setup_prompt_for_feed

	echo "updating feeds..."
	opkg update &>/dev/null

	dev_setup_package_installed vespera && installed=1 || installed=0

	if ((installed==0)); then
		dev_setup_prompt_run_yes_no "Install vespera" opkg install vespera \
			&& installed=1 || installed=0
	fi

	if ((installed==1)); then
		dev_setup_package_installed "mount-shares" && installed=1 || installed=0
		if ((installed==0)); then
			dev_setup_prompt_run_yes_no "Install mount-shares" opkg install mount-shares \
				&& installed=1 || installed=0
		fi
	fi

	if ((installed==1)) ; then
		mountpoint -q "$dev_mount_point" ||
			dev_setup_prompt_run_yes_no "Setup dev share" dev_setup_share \
				&& installed=1 || installed=0
	fi
	ls -L "$dev_link" &>/dev/null && echo "✅ dev share setup" || echo "⚠️ dev share not setup"

	if [[ ! -L ~/.vscode-server ]]; then
		dev_setup_prompt_run_yes_no "Setup vscode on external drive" setup_vs_code_drive
	else
		echo "✅ vscode-server already sym-linked: $(readlink -f ~/.vscode-server) -> ~/.vscode-server"
	fi

	((installed==0)) &&
		dev_setup_create_dev_symlink

	dev_setup_default_path

	dev_setup_profile
}


dev_setup_help() {
	echo "dev-setup setup"
	echo "dev-setup set-feed"
	local feedconf=$(readlink /etc/opkg/vespera.conf)
	echo "feed set to:$feedconf"

}

case "${1:-}" in
	--help|help|"")
		dev_setup_help
		;;
	--setup|setup)
		shift
		dev_setup
		;;
	--set-feed|set-feed)
		shift
		dev_setup_set_feed "${1:-develop}"
		;;
	*)
		echo "ERROR: Unknown command: ${1}" >&2
		dev_setup_help >&2
		exit 1
		;;
	esac
