#!/usr/bin/env bash

set -o nounset

export RUNNING_FROM_GUI=1

[[ -z "${__SOURCE_COMMON_SOURCED:-}" ]] && {
	# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
	source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common" && __SOURCE_COMMON_SOURCED=1
}

addsource "lang-common"
addsource "dbus-common"
addsource "service-common"
addsource "serial-device-installer"

declare DEFAULT_USB_PROPS="ID_MODEL,ID_VENDOR,ID_SERIAL,ID_PATH"

device_remove() {

	DEVICE_SID="${1}"
	[[ -z "$DEVICE_SID" ]] && { echo "Invalid argument: sid empty" >&2; return 1; }

	echo_lang "$LANG_DEVICE_REMOVING_SERIAL_DEVICE_SERVICE"
	serial_device_installer_remove_service

	echo_lang "$LANG_DEVICE_REMOVING_DEVICE_SETTINGS_ARG1" "sid_${DEVICE_SID}"
	dbus_common_delete_tree "/Settings/Devices/sid_${DEVICE_SID}" 1>/dev/null

	return 0
}

device_scan_usb() {
	local tty
	local usbProps=

	for tty in $(serial_device_installer_get_available_devices); do

		serial_device_installer_fill_usb_props "$tty" "$DEFAULT_USB_PROPS" usbProps || { continue; }

		serial_device_installer_set_device_sid "$usbProps"
		usbProps=$(printf '%s\n' "$usbProps" | sed 's/,\?ID_PATH=[^,]*//')

		# The opkg-manager service is responsible for adding the dbus settings
		# so just pass the values we have
		printf 'DEVICE:DISCOVERED\t%s\t%s\t%s\n' "$DEVICE_SID" "$tty" "$usbProps"
	done

	return 0
}

device_bind_usb_to_service() {
	local sid="$1"
	local tty="$2"
	local device_path="$3"
	local jsonUsbProps="$4"
	local usbProps

	test -e "/dev/$tty" \
		|| { echo "Error: tty ($tty) does not exist" >&2; return 1; }

	[[ $(serial_device_installer_get_available_devices "/dev/${tty}") != "${tty}" ]] \
		&& { echo "Error: tty ($tty) is not available" >&2; return 1; }

	serial_device_installer_fill_usb_props "${tty}" "${DEFAULT_USB_PROPS}" usbProps
	serial_device_installer_set_device_sid "${usbProps}" # hashed usbProps

	[[ "${sid}" != "${DEVICE_SID}" ]] && {
		echo "Error: Device changed" >&2 ; return 1; }

	# get dbus values
	local service_name=
	dbus_common_get_value "/Settings/OpkgManager/CustomServices/${device_path}/ServiceName" service_name
	[[ -z "${service_name}" ]] &&
		{ echo "Error: Service name not found" >&2; return 1; }

	# fill serial-starter-installer variables
	# shellcheck disable=SC2034
	DEVICE_UDEV_PROPS="${usbProps}";
	# shellcheck disable=SC2034
	DEVICE_TTY="${tty}"
	# shellcheck disable=SC2034
	DEVICE_SERVICE_NAME="${service_name}"

	# echo "DEVICE_TTY=${tty}, DEVICE_SERVICE_NAME=${service_name}, DEVICE_UDEV_PROPS=${usbProps}"

	serial_device_installer_install 1>/dev/null || return 1

	dbus_common_set_string_value "/Settings/Devices/sid_${sid}/UsbProps" "${jsonUsbProps}" 1>/dev/null

	find /var/volatile/services -type d -name "*.${DEVICE_TTY}" \
			! -name "${service_name}.${DEVICE_TTY}" -exec rm -rf {} +

	# Remove stale service symlinks
	find -L /service -maxdepth 1 -type l -delete

	# The opkg-manager service is responsible for adding the dbus settings
	# so just pass that we have claimed the device.
	printf 'DEVICE:CLAIMED\t%s\n' "${DEVICE_SID}"

	# In demo mode the serial starter-service is down
	# so manualy create and start the service in this case
	local demo_mode=
	dbus_common_get_value "/Settings/Gui/DemoMode" demo_mode

	[[ -n $demo_mode ]] && {
		#echo "opkg-manager: Venus OS in demo mode, manualy starting service"
		service_common_start_templated_service "${tty}" "${service_name}"
	}
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	case "${1:-}" in
		remove)
			shift
			device_remove "${1:-}";;
		scan)
			shift
			device_scan_usb;;
		bind)
			shift
			device_bind_usb_to_service "$@";;
		*)
			if [[ -n ${1:-} ]]; then
				echo "device: invalid command : ${1}" >&2
			fi
			;;
	esac
fi
