#!/bin/bash
# shellcheck disable=SC2317,SC2329  # Don't warn about unreachable commands in this file

set -o nounset
export RUNNING_FROM_GUI=1

 [[ -z "${__SOURCE_COMMON_SOURCED:-}" ]] && {
	# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
	source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common" && __SOURCE_COMMON_SOURCED=1
}
addsource "opkg-common"

__feed_command() {
	local retVal=

	feed_editor "${1:-}" "${2:-}" "${3:-}" "${4:-}"
	retVal=$?

	if [[ $retVal == 0 ]]; then
		local this_path; this_path=$(dirname "${BASH_SOURCE[0]}")
	  	"$this_path/opkg-json-indexer" update force # update cached json
	fi

	return $retVal
}

case "${1:-}" in
  add)
		__feed_command "add" "${2:-}" "${3:-}" "${4:-}"
		;;
  edit)
		__feed_command "edit" "${2:-}" "${3:-}" "${4:-}"
		;;
  remove)
		__feed_command "remove" "${2:-}" "" ""
		;;
  set)
    opkg_common_set_feed "${2:-}"
		;;
  type)
		feed_get_feed_type
		;;
	*)
		if [[ -n ${1:-} ]]; then
			echo "feed: incorrect command : ${1}" >&2
		fi
		;;
esac
