#!/bin/bash

# shellcheck disable=SC2317,SC2329  # Don't warn about unreachable commands in this file

set -o nounset
export RUNNING_FROM_GUI=1

[[ -z "${__SOURCE_COMMON_SOURCED:-}" ]] && {
	# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
	source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common" && __SOURCE_COMMON_SOURCED=1
}
addsource "opkg-common"
addsource "lang-common"
addsource "/libs/log-lib"

__validate_package_name() {
  if [[ -z "$1" ]]; then
    log_error "package_commond: package name not supplied"
    return 1
  fi
  return 0
}

__package_set_install_lock() {
	mkdir -p /var/lock/
	touch /var/lock/opkg-manager-install
}
__package_clear_install_lock() {
	rm -f /var/lock/opkg-manager-install
}

__package_command() {
	local action_msg="${1}"

  shift 1 # rest are opkg args

  __init_root_fs_for_writing

	local this_path; this_path=$(dirname "${BASH_SOURCE[0]}")

	echo_lang "$LANG_PACKAGE_UPDATING_PACKAGES"
  "$this_path/opkg-json-indexer" update force 1>/dev/null # update packages and json

	__cleanup() {
		__package_clear_install_lock
		opkg_common_clear_requested_package_update
	}
	trap '__cleanup' RETURN

	__package_clear_install_lock
  __package_set_install_lock

  opkg "$@"
	local -i status=$?

	__package_clear_install_lock

	#opkg_common_package_update_requested && {
		#opkg_common_clear_requested_package_update
		echo_lang "$LANG_PACKAGE_UPDATING_PACKAGES"
    "$this_path/opkg-json-indexer" update force 1>/dev/null # update packages and json
	#}

  __restore_previous_fs_access

	if [[ $status == 0 ]]; then
    echo_lang "$LANG_PACKAGE_SUCCEEDED" "$action_msg"
  else
    echo_lang "$LANG_PACKAGE_ARG1_FAILED_ARG2" "$action_msg" "$status"
  fi

  return $status
}

# Helper to install a package and log output/errors
package_install() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  echo_lang "${LANG_PACKAGE_INSTALLING_ARG1}" "$@"

  __package_command "${LANG_PACKAGE_INSTALL}" install "$@"

}
__status_message() {
  local status="${1}"
  local action="${2}"
  if [[ $status == 0 ]]; then
    echo_lang "$LANG_PACKAGE_SUCCEEDED" "$action"
  else
	  echo_lang "$LANG_PACKAGE_ARG1_FAILED_ARG2" "$action" "$status"
  fi
}

package_upgrade() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  echo_lang "$LANG_PACKAGE_UPGRADING_ARG1" "$*"

  __package_command "$LANG_PACKAGE_UPGRADE" upgrade "$@"

}

package_remove() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  if [[ -z $(opkg list-installed "${package_name}") ]]; then
    log "Not Installed ${package_name}, exiting"
    return 0
  fi

  echo_lang "$LANG_PACKAGE_REMOVING_ARG1" "$*"
  __package_command "$LANG_PACKAGE_REMOVE" remove "$@"

}

case "${1:-}" in
  install)
    shift
    package_install "$@"
    ;;
  remove)
    shift
    package_remove "$@"
    ;;
  upgrade)
    shift
    package_upgrade "$@"
    ;;
  *)
    if [[ -n ${1:-} ]]; then
      echo "package: incorrect command : ${1}" >&2
    fi
    ;;
esac
