#!/bin/bash

set -o nounset

declare this_path; this_path="$(dirname "${BASH_SOURCE[0]}")"

QML_TARGET_PATH="/opt/victronenergy/gui/qml"
QML_SOURCE_PATH="$this_path/../src${QML_TARGET_PATH}"

[[ -d "${QML_TARGET_PATH}" ]] || {
	 echo "Wrong Server! (path not found ${QML_TARGET_PATH})"; exit 1;
}

QML_ICONS_TARGET_PATH="/opt/victronenergy/themes/ccgx/icons"
QML_ICONS_SOURCE_PATH="$this_path/../src${QML_ICONS_TARGET_PATH}"

# qml: files link all files found in $QML_ICONS_SOURCE_PATH
for source_file in "$QML_SOURCE_PATH"/*; do
	[ -f "$source_file" ] || continue
	dest_file="$(basename "$source_file")"
	echo "$source_file -> $QML_TARGET_PATH/$dest_file"
	rm -f "$QML_TARGET_PATH/$dest_file"
	ln -sf "$source_file" "$QML_TARGET_PATH/$dest_file"
done

# icons: link all files found in $QML_ICONS_SOURCE_PATH
for source_file in "$QML_ICONS_SOURCE_PATH"/*; do
	[ -f "$source_file" ] || continue
	dest_file="$(basename "$source_file")"
	echo "$source_file -> $QML_ICONS_TARGET_PATH/$dest_file"
	rm -f "$QML_ICONS_TARGET_PATH/$dest_file"
	ln -sf "$source_file" "$QML_ICONS_TARGET_PATH/$dest_file"
done

SERVICE_TARGET_PATH="/opt/victronenergy/dbus-inetbox"
SERVICE_SOURCE_PATH="$this_path/../src${SERVICE_TARGET_PATH}"
echo "$SERVICE_SOURCE_PATH -> $SERVICE_TARGET_PATH"
rm -rf "$SERVICE_TARGET_PATH"
ln -sf "$SERVICE_SOURCE_PATH" "$SERVICE_TARGET_PATH"

SERVICE_TEMPLATES_TARGET_PATH="/opt/victronenergy/service-templates/dbus-inetbox"
SERVICE_TEMPLATES_SOURCE_PATH="$this_path/../src${SERVICE_TEMPLATES_TARGET_PATH}"
rm -rf "$SERVICE_TEMPLATES_TARGET_PATH"
cp -rf "$SERVICE_TEMPLATES_SOURCE_PATH" "$SERVICE_TEMPLATES_TARGET_PATH"

# $this_path/../src/data/apps/dbus-inetbox/installer "dev-install"

echo "done"
