#!/bin/bash


MOUNT_SHARES_CONF=/data/conf/mount-shares.conf

if [[ ! -f "/data/apps/available/mount-shares/2-rc-startup" ]]; then
	echo "Installing mount shares..."

	RC_LOCAL="/data/rc.local"
	RC_LOCAL_LINE='[[ ! -f /data/apps/vespera/vespera ]] && /data/apps/available/mount-shares/2-rc-startup'

	[[ ! -f "$RC_LOCAL" ]] && { touch "$RC_LOCAL" && chmod +x "$RC_LOCAL"; }
	! grep -Fqx "$RC_LOCAL_LINE" "$RC_LOCAL" && echo "$RC_LOCAL_LINE" >> "$RC_LOCAL"

	mkdir -p /data/apps/available/mount-shares
	chmod +x "${0}"
	mv "${0}" /data/apps/available/mount-shares/2-rc-startup

fi

if [[ -f $MOUNT_SHARES_CONF ]]; then
	while IFS= read -r line; do
			[ -z "$line" ] && continue
			[[ "$line" == \#* ]] && continue
			# shellcheck disable=SC2086
			busybox mount $line
	done < "$MOUNT_SHARES_CONF"
fi
