#!/usr/bin/env bash
# shellcheck disable=SC2034

PACKAGE_CUSTOM_MENUS="PageSettingsDisplay/ThemerPageSettingsSubMenu"

DBUS_AVAILABLE_THEMES="Dark" # space separated list of themes
PACKAGE_DBUS_SETTINGS='
		{"path":"/Settings/Themer/AvailableThemes", "default":"Dark"}
	  {"path":"/Settings/Themer/CurrentTheme", "default":""}
		{"path":"/Settings/Themer/Themes/Dark/TextColor", "default":"#ffffff"}
		{"path":"/Settings/Themer/Themes/Dark/WindowBackgroundColor", "default":"#202020"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundColor", "default":"#202020"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundColorSelected", "default":"#4790d0"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundColor2", "default":"#313131"}
		{"path":"/Settings/Themer/Themes/Dark/IconSuffixNormal", "default":"-active"}
		{"path":"/Settings/Themer/Themes/Dark/IconSuffixSelected", "default":"-active"}
		{"path":"/Settings/Themer/Themes/Dark/BorderColor", "default":"#3c3c3c"}
		{"path":"/Settings/Themer/Themes/Dark/ServiceBackgroundColor", "default":"#b07c04"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundColorSelected", "default":"#2969a1"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundTankColor", "default":"#cccccc"}
		{"path":"/Settings/Themer/Themes/Dark/BackgroundTankColor", "default":"#cccccc"}
		{"path":"/Settings/Themer/Themes/Dark/Color2", "default":"#c4c4c4"}
'

#PACKAGE_DBUS_SETTINGS_DEPRECATED=""

pre_install() {

	# 1. add themes to existing cvs list
	local new_themes cur_themes
	dbus_lib_get_value "/Settings/Themer/AvailableThemes" cur_themes
	new_themes="$cur_themes"

	for theme in $DBUS_AVAILABLE_THEMES; do
			[[ ",$new_themes," == *,"$theme",* ]] ||
					new_themes="${new_themes:+$new_themes,}$theme"
	done

	[[ "$new_themes" != "$cur_themes" ]] &&
			dbus_lib_set_value "/Settings/Themer/AvailableThemes" "$new_themes"

}

pre_remove() {
	local new_themes cur_themes

	# 1. remove themes from existing cvs list
	dbus_lib_get_value "/Settings/Themer/AvailableThemes" cur_themes
	new_themes=

	for theme in ${cur_themes//,/ }; do
		[[ " $DBUS_AVAILABLE_THEMES " == *" $theme "* ]] || new_themes="${new_themes:+$new_themes,}$theme"
	done

	[[ "$new_themes" != "$cur_themes" ]] &&
		dbus_lib_set_value "/Settings/Themer/AvailableThemes" "$new_themes"
}

# shellcheck source=/data/dev/addons/vespera/src/data/apps/vespera/libs/source-lib
source "${VESPERA_ROOT:-}/data/apps/vespera/libs/source-lib"
addsource libs/installer-lib "$@"
