#!/bin/bash

echo "*** starting $(basename "$(dirname "$(realpath "$0")")") ***"
exec 2>&1

# load the variables from the network-gps.conf
# network-gps.conf is created in the
# shellcheck disable=SC1091
. /data/conf/network-gps.conf

# shellcheck disable=SC2086

# route gps from router to serial port
if [[ ! -e /dev/$NETWORK_GPS_DEVICE ]]; then
  echo /dev/$NETWORK_GPS_DEVICE does not exist, starting socat....
  /usr/bin/socat -u -dd "UDP4-RECV:$NETWORK_GPS_PORT" "pty,link=/dev/$NETWORK_GPS_DEVICE,raw,nonblock,echo=0,b$NETWORK_GPS_BAUD" &
fi

# add a friendly name to display in the venus os gps settings
if [[ -n "$NETWORK_GPS_NAME" ]]; then
  (
    while true; do
      sleep 6
      dbus -y "com.victronenergy.gps.ve_$NETWORK_GPS_DEVICE" / GetValue &>/dev/null
      declare -i r=$?
      if ((r==0)); then
        echo "set victron dbus device name $NETWORK_GPS_NAME"
        dbus -y "com.victronenergy.gps.ve_$NETWORK_GPS_DEVICE" /ProductName SetValue "$NETWORK_GPS_NAME"
        break
      fi
    done
  ) &
fi

# start the gps dbus service
# -s is serial port to use
exec /opt/victronenergy/gps-dbus/gps_dbus -s "/dev/$NETWORK_GPS_DEVICE"
